from education_system.post_18.university_system.modules.domain.academics.mitigating_circumstances.services.mitigating_circumstances_service import MitigatingCircumstancesService

__all__ = ["MitigatingCircumstancesService"]
