"""Centralised file/directory paths for the Primary School System.

Environment override: ``EDU_PRIMARY_DATA_DIR``.
"""

from __future__ import annotations

import os
from pathlib import Path

PACKAGE_ROOT: Path = Path(__file__).resolve().parent.parent

DATA_DIR: Path = Path(
    os.environ.get("EDU_PRIMARY_DATA_DIR")
    or (PACKAGE_ROOT / "data")
).resolve()

# All primary modules share a single SQLite DB.
PUPILS_DB: Path = DATA_DIR / "primary.db"
ADMISSIONS_DB: Path = PUPILS_DB
ENROLMENT_DB: Path = PUPILS_DB
ONBOARDING_DB: Path = PUPILS_DB
ACADEMIC_YEAR_DB: Path = PUPILS_DB
CALENDAR_DB: Path = PUPILS_DB

# Pastoral / governance modules ported from secondary share the DB.
EQUALITY_DIVERSITY_DB: Path = PUPILS_DB
COMPLAINTS_DB: Path = PUPILS_DB
FEEDBACK_DB: Path = PUPILS_DB
SURVEYS_DB: Path = PUPILS_DB
SCHOOL_COUNCIL_DB: Path = PUPILS_DB
TRANSPORT_DB: Path = PUPILS_DB

STAFF_DB: Path = PUPILS_DB
STAFF_HR_DB: Path = PUPILS_DB
DEPARTMENTS_DB: Path = PUPILS_DB
STAFF_ABSENCE_DB: Path = PUPILS_DB
STAFF_WELLBEING_DB: Path = PUPILS_DB
RECRUITMENT_DB: Path = PUPILS_DB
APPRAISALS_DB: Path = PUPILS_DB
CPD_DB: Path = PUPILS_DB
DBS_CHECKS_DB: Path = PUPILS_DB
VISITORS_DB: Path = PUPILS_DB
PARENT_CONTACTS_DB: Path = PUPILS_DB
PARENTS_EVENINGS_DB: Path = PUPILS_DB
NOTICES_DB: Path = PUPILS_DB
ANNOUNCEMENTS_DB: Path = PUPILS_DB
NOTIFICATIONS_DB: Path = PUPILS_DB
ACTIVITY_FEED_DB: Path = PUPILS_DB
MESSAGES_DB: Path = PUPILS_DB
LETTER_TEMPLATES_DB: Path = PUPILS_DB
DOCUMENT_HUB_DB: Path = PUPILS_DB
ATTACHMENTS_DB: Path = PUPILS_DB

FEES_DB: Path = PUPILS_DB
TRIPS_DB: Path = PUPILS_DB
RECEIPTS_DB: Path = PUPILS_DB
EXPENSE_CLAIMS_DB: Path = PUPILS_DB
FUNDING_DB: Path = PUPILS_DB
CENSUS_DB: Path = PUPILS_DB

PROGRESS_DB: Path = PUPILS_DB
AUDIT_REPORTS_DB: Path = PUPILS_DB
DATA_EXPORT_DB: Path = PUPILS_DB

SETTINGS_DB: Path = PUPILS_DB
COMPLIANCE_DB: Path = PUPILS_DB
GOVERNANCE_DB: Path = PUPILS_DB
POLICIES_DB: Path = PUPILS_DB
GDPR_DB: Path = PUPILS_DB
RISK_MANAGEMENT_DB: Path = PUPILS_DB
HEALTH_SAFETY_DB: Path = PUPILS_DB
ASSETS_DB: Path = PUPILS_DB
TODO_DB: Path = PUPILS_DB


def ensure_directories() -> None:
    DATA_DIR.mkdir(parents=True, exist_ok=True)
