"""Shared alumni service imports for the alumni GUI mixins."""

from education_system.post_18.university_system.modules.domain.student_affairs.services.alumni_management import (
    create_alumni_story,
    create_enhanced_event,
    create_fundraising_campaign,
    create_newsletter,
    event_check_in_system,
    generate_alumni_report,
    generate_engagement_recommendations,
    get_connection,
    init_alumni_db,
    manage_alumni_forum,
    manage_business_directory,
    manage_class_reunions,
    manage_photo_gallery,
    manage_regional_chapters,
    post_job_opportunity,
    record_donation,
    register_alumni,
    schedule_career_counseling,
    search_alumni_directory,
    set_auth,
    setup_alumni_directory,
    setup_alumni_permissions,
    setup_mentorship,
    smart_mentorship_matching,
    update_alumni,
    view_alumni,
    view_alumni_stories,
    view_connection_requests,
    view_donations,
    view_engagement_leaderboard,
    view_events,
    view_fundraising_campaigns,
    view_job_board,
    view_mentorships,
    view_my_badges,
)

