import tkinter as tk
from education_system.post_18.university_system.infrastructure.email.template_utils import render_template
from tkinter import ttk, messagebox, simpledialog, filedialog
from tkinter.scrolledtext import ScrolledText
from education_system.post_18.university_system.infrastructure.database.db import sqlite3, get_connection as db_get_connection
from education_system.post_18.university_system.core import paths
from datetime import datetime, timedelta
from pathlib import Path
import threading
import shutil
from functools import partial

# Import internationalization (i18n) for multi-language support
try:
    from education_system.post_18.university_system.core.i18n import (
        get_text as _t,
        get_current_language,
    )
    I18N_AVAILABLE = True
except ImportError:
    I18N_AVAILABLE = False
    _t = lambda key, **kwargs: kwargs.get("default", key)
    get_current_language = lambda: "en"

# Alumni service functions
from education_system.post_18.university_system.modules.domain.student_affairs.gui.alumni._service_imports import (
    init_alumni_db, register_alumni, view_alumni, update_alumni,
    view_events, create_enhanced_event, event_check_in_system,
    record_donation, view_donations, setup_mentorship, view_mentorships,
    search_alumni_directory, view_connection_requests, manage_business_directory,
    create_newsletter, manage_alumni_forum, post_job_opportunity, view_job_board,
    schedule_career_counseling, view_fundraising_campaigns, create_fundraising_campaign,
    view_engagement_leaderboard, view_my_badges, manage_photo_gallery,
    manage_class_reunions, manage_regional_chapters, setup_alumni_directory,
    generate_alumni_report, set_auth, setup_alumni_permissions,
    smart_mentorship_matching, generate_engagement_recommendations,
    create_alumni_story, view_alumni_stories, get_connection,
)



class ReportsMixin:
        def _email_report_to_admin(self, output_widget=None):
            """Email current report to admin via the email system."""
            widget = output_widget if output_widget is not None else self.report_output
            report_content = widget.get(1.0, tk.END).strip()
            if not report_content or report_content.startswith("Select a quick report"):
                messagebox.showwarning("No Report", "Please generate a report first before emailing.")
                return

            try:
                # Import required modules
                from education_system.post_18.university_system.infrastructure.database.db import get_connection
                from education_system.post_18.university_system.infrastructure.email.email_service import send_email

                # Get admin email from database
                admin_email = None
                try:
                    with get_connection() as conn:
                        cursor = conn.execute("""
                            SELECT email FROM users
                            WHERE role = 'admin' AND email IS NOT NULL AND email != ''
                            LIMIT 1
                        """)
                        admin_row = cursor.fetchone()
                        if admin_row and admin_row[0]:
                            admin_email = admin_row[0]
                except sqlite3.Error as e:
                    print(f"Warning: Could not fetch admin email: {e}")

                # Fall back to the canonical configured admin address.
                if not admin_email:
                    try:
                        from education_system.post_18.university_system.core.defaults import get_admin_email
                        admin_email = get_admin_email()
                    except Exception:
                        admin_email = None

                if not admin_email:
                    messagebox.showerror("Error", "No admin email found")
                    return

                # Use template for email
                template_vars = {
                    'report_date': datetime.now().strftime('%Y-%m-%d %H:%M:%S'),
                    'report_content': report_content
                }

                subject, body = render_template('alumni_report_admin', template_vars)

                if not subject or not body:
                    # Fallback if template fails
                    subject = f"Alumni Report - {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}"
                    body = f"Alumni Report\n\nGenerated by: Alumni Management System\nDate: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n\n"
                    body += "-" * 50 + "\n\n"
                    body += report_content

                result = send_email(admin_email, subject, body)

                if result:
                    messagebox.showinfo("Success", f"Report emailed successfully to {admin_email}")
                else:
                    messagebox.showinfo("Queued", f"Report has been queued for delivery to {admin_email}")

            except ImportError:
                messagebox.showerror("Error", "Email service is not available. Please check email configuration.")
            except (sqlite3.Error, AttributeError) as e:
                messagebox.showerror("Error", f"Failed to send email: {str(e)}")

        def _generate_custom_report_content(self):
            """Generate custom report based on selected sections"""
            selected = [key for key, var in self.report_sections.items() if var.get()]
            if not selected:
                self.report_output.insert(tk.END, "Please select at least one section to include in the report.")
                return

            report = f"CUSTOM ALUMNI REPORT\nGenerated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n"
            report += f"Date Range: {self.report_start_date.get()} to {self.report_end_date.get()}\n"
            report += "=" * 50 + "\n\n"
            report += f"Sections included: {', '.join(selected)}\n\n"
            report += "Report data would be generated based on selected criteria.\n"
            self.report_output.insert(tk.END, report)

        def _generate_donation_report_content(self):
            """Generate donation report content"""
            report = self._get_donation_report_text()
            self.report_output.insert(tk.END, report)

        def _generate_engagement_report_content(self):
            """Generate engagement report content"""
            report = self._get_engagement_report_text()
            self.report_output.insert(tk.END, report)

        def _generate_report_in_window(self, report_type):
            """Generate the report and open it in its own window."""
            if report_type == 'summary':
                content = self._get_alumni_summary_text()
            elif report_type == 'engagement':
                content = self._get_engagement_report_text()
            elif report_type == 'donation':
                content = self._get_donation_report_text()
            elif report_type == 'custom':
                content = self._build_custom_report_text()
            else:
                content = "Unknown report type."
            self._open_report_window(report_type, content)

        def _open_report_window(self, report_type, content):
            """Show a generated report in a new window with Save-as-TXT and
            Email-to-Admin actions wired to the email system."""
            win = tk.Toplevel(self.root)
            win.title(f"{str(report_type).title()} Report")
            win.geometry("820x620")
            out = ScrolledText(win, wrap=tk.WORD)
            out.pack(fill=tk.BOTH, expand=True, padx=10, pady=10)
            out.insert(tk.END, content)

            btns = ttk.Frame(win)
            btns.pack(fill=tk.X, padx=10, pady=(0, 10))
            ttk.Button(btns, text="💾 Save as TXT",
                       command=lambda: self._save_report_as_txt(out)).pack(side=tk.LEFT, padx=(0, 10))
            ttk.Button(btns, text="✉ Email to Admin",
                       command=lambda: self._email_report_to_admin(out)).pack(side=tk.LEFT, padx=(0, 10))
            ttk.Button(btns, text="Close", command=win.destroy).pack(side=tk.RIGHT)

            # Mirror into the inline panel too, if the reports view built one.
            try:
                self.report_output.delete(1.0, tk.END)
                self.report_output.insert(tk.END, content)
            except (AttributeError, tk.TclError):
                pass

        def _build_custom_report_text(self):
            """Build the custom report text from the selected sections."""
            selected = [key for key, var in self.report_sections.items() if var.get()]
            if not selected:
                return "Please select at least one section to include in the report."
            report = f"CUSTOM ALUMNI REPORT\nGenerated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n"
            report += f"Date Range: {self.report_start_date.get()} to {self.report_end_date.get()}\n"
            report += "=" * 50 + "\n\n"
            report += f"Sections included: {', '.join(selected)}\n\n"
            report += "Report data would be generated based on selected criteria.\n"
            return report

        def _generate_summary_report_content(self):
            """Generate summary report content"""
            report = self._get_alumni_summary_text()
            self.report_output.insert(tk.END, report)

        def _get_alumni_summary_text(self):
            """Return alumni summary report text"""
            return f"""ALUMNI SUMMARY REPORT
    Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
    ==================================================

    OVERALL STATISTICS
    Total Alumni: 1,247
    Active Alumni (last 6 months): 342 (27.4%)
    New Registrations (this year): 89
    Average Graduation Year: 2016

    ENGAGEMENT METRICS
    Total Engagement Points: 124,750
    Average Points per Alumni: 100.0
    Most Engaged Alumni: Sarah Johnson (1,250 points)
    Engagement Growth (vs. last year): +23%

    DEMOGRAPHICS
    By Graduation Decade:
    - 2020s: 387 alumni (31.0%)
    - 2010s: 445 alumni (35.7%)
    - 2000s: 298 alumni (23.9%)
    - 1990s: 117 alumni (9.4%)

    By Industry:
    - Technology: 342 alumni (27.4%)
    - Healthcare: 187 alumni (15.0%)
    - Finance: 156 alumni (12.5%)
    - Education: 134 alumni (10.7%)
    - Other: 428 alumni (34.3%)

    GEOGRAPHIC DISTRIBUTION
    Top Locations:
    - San Francisco Bay Area: 234 alumni
    - New York City: 178 alumni
    - Los Angeles: 145 alumni
    - Boston: 123 alumni
    - International: 189 alumni

    Report Generated Successfully
    """

        def _get_donation_report_text(self):
            """Return donation report text"""
            return f"""DONATION ANALYSIS REPORT
    Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
    ========================================

    FINANCIAL OVERVIEW
    Report Period: January 1, 2025 - December 6, 2025
    Total Donations: £234,750
    Number of Donors: 156
    Average Donation: £1,505
    Growth vs. Previous Year: +18%

    DONATION STATISTICS
    Total Transactions: 298
    - One-time donations: 234 (78.5%)
    - Recurring donations: 64 (21.5%)

    CAMPAIGN PERFORMANCE
    Annual Alumni Fund: £156,750 (66.8%) - Goal: 156.8%
    Scholarship Fund: £45,600 (19.4%) - Goal: 91.2%
    Building Fund: £23,400 (10.0%) - Goal: 93.6%
    Emergency Fund: £9,000 (3.8%) - Goal: 60.0%

    MAJOR DONORS (>£1,000)
    1. Anonymous: £25,000 (Building Fund)
    2. Johnson Family Foundation: £15,000 (Scholarship)
    3. Tech Innovations Inc.: £10,000 (Annual Fund)
    4. Dr. Martinez: £7,500 (Emergency Fund)
    5. Chen Financial Group: £5,000 (Annual Fund)

    Overall Grade: A- (Strong Performance)
    Fundraising Health: Excellent

    Report Generated Successfully
    """

        def _get_engagement_report_text(self):
            """Return engagement report text"""
            return f"""ALUMNI ENGAGEMENT REPORT
    Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
    =============================================

    ENGAGEMENT OVERVIEW
    Report Period: January 1, 2025 - December 6, 2025
    Total Active Users: 342
    Total Activities: 2,847
    Average Activities per User: 8.3

    TOP PERFORMERS
    1. Sarah Johnson: 1,250 points (45 activities)
    2. Michael Chen: 1,100 points (38 activities)
    3. Dr. Lisa Martinez: 950 points (32 activities)
    4. Emily Davis: 825 points (28 activities)
    5. John Smith: 750 points (25 activities)

    ACTIVITY BREAKDOWN
    Event Participation: 445 activities (15.6%)
    Forum Engagement: 567 activities (19.9%)
    Networking Activities: 389 activities (13.7%)
    Content Contribution: 234 activities (8.2%)
    Career Services: 445 activities (15.6%)
    Giving & Donations: 178 activities (6.3%)
    Other Activities: 589 activities (20.7%)

    ENGAGEMENT TRENDS
    Monthly Active Users Growth: +46% year-over-year
    Engagement Score: 8.3/10 (Excellent)
    Trend: Increasing

    Report Generated Successfully
    """

        def _save_report_as_txt(self, output_widget=None):
            """Save current report as a TXT file"""
            widget = output_widget if output_widget is not None else self.report_output
            report_content = widget.get(1.0, tk.END).strip()
            if not report_content or report_content.startswith("Select a quick report"):
                messagebox.showwarning("No Report", "Please generate a report first before saving.")
                return

            file_path = filedialog.asksaveasfilename(
                defaultextension=".txt",
                filetypes=[("Text files", "*.txt"), ("All files", "*.*")],
                initialfile=f"alumni_report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.txt"
            )

            if file_path:
                try:
                    with open(file_path, 'w', encoding='utf-8') as f:
                        f.write(report_content)
                    messagebox.showinfo("Success", f"Report saved successfully to:\n{file_path}")
                except (OSError, IOError) as e:
                    messagebox.showerror("File Error", f"Failed to save report: {str(e)}")

        def generate_alumni_summary(self):
            """Generate alumni summary report"""
            self.report_output.delete(1.0, tk.END)

            summary_report = f"""ALUMNI SUMMARY REPORT
    Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
    ==================================================

    📊 OVERALL STATISTICS
    Total Alumni: 1,247
    Active Alumni (last 6 months): 342 (27.4%)
    New Registrations (this year): 89
    Average Graduation Year: 2016

    📈 ENGAGEMENT METRICS
    Total Engagement Points: 124,750
    Average Points per Alumni: 100.0
    Most Engaged Alumni: Sarah Johnson (1,250 points)
    Engagement Growth (vs. last year): +23%

    🎓 DEMOGRAPHICS
    By Graduation Decade:
    • 2020s: 387 alumni (31.0%)
    • 2010s: 445 alumni (35.7%)
    • 2000s: 298 alumni (23.9%)
    • 1990s: 117 alumni (9.4%)

    By Industry:
    • Technology: 342 alumni (27.4%)
    • Healthcare: 187 alumni (15.0%)
    • Finance: 156 alumni (12.5%)
    • Education: 134 alumni (10.7%)
    • Other: 428 alumni (34.3%)

    🌍 GEOGRAPHIC DISTRIBUTION
    Top Locations:
    • San Francisco Bay Area: 234 alumni
    • New York City: 178 alumni
    • Los Angeles: 145 alumni
    • Boston: 123 alumni
    • International: 189 alumni

    💼 CAREER ACHIEVEMENTS
    Current Roles:
    • Senior/Executive Level: 234 alumni (18.8%)
    • Mid-Level Professional: 445 alumni (35.7%)
    • Early Career: 298 alumni (23.9%)
    • Entrepreneurs: 89 alumni (7.1%)
    • Students/Transitioning: 181 alumni (14.5%)

    📞 CONTACT PREFERENCES
    • Email: 1,156 alumni (92.7%)
    • Phone: 234 alumni (18.8%)
    • LinkedIn: 567 alumni (45.5%)
    • Platform Messages: 345 alumni (27.7%)

    🎯 KEY INSIGHTS
    • Technology and Healthcare sectors show highest engagement
    • Class of 2015-2020 most active in alumni activities
    • West Coast concentration (47% of active alumni)
    • Strong correlation between recent graduation and engagement
    • Mentorship program participation growing 15% annually

    📋 RECOMMENDATIONS
    1. Increase outreach to 2000s graduates
    2. Develop industry-specific programming
    3. Expand international chapter presence
    4. Enhance mobile platform engagement
    5. Create mid-career focused content

    Report Generated Successfully ✓
    """

            # Insert the generated summary report into the text widget and update the status
            self.report_output.insert(tk.END, summary_report)
            self.update_status("Alumni summary report generated")

        def generate_custom_report(self):
            """Generate custom report based on selected parameters"""
            # Collect selected sections
            selected_sections = [key for key, var in self.report_sections.items() if var.get()]

            if not selected_sections:
                messagebox.showwarning("No Sections Selected", "Please select at least one report section.")
                return

            self.report_output.delete(1.0, tk.END)

            custom_report = f"""CUSTOM ALUMNI REPORT
    Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
    Report Period: {self.report_start_date.get()} to {self.report_end_date.get()}
    Output Format: {self.report_format.get()}
    ========================================================================================

    """

            if 'demographics' in selected_sections:
                custom_report += """📊 ALUMNI DEMOGRAPHICS
    Total Alumni in Period: 1,247
    New Registrations: 89
    Active Alumni: 342 (27.4%)

    Age Distribution:
    • 20-25 years: 234 alumni (18.8%)
    • 26-30 years: 456 alumni (36.6%)
    • 31-35 years: 298 alumni (23.9%)
    • 36-40 years: 187 alumni (15.0%)
    • 40+ years: 72 alumni (5.8%)

    Gender Distribution:
    • Female: 623 alumni (49.9%)
    • Male: 587 alumni (47.1%)
    • Other/Not specified: 37 alumni (3.0%)

    """

            if 'engagement' in selected_sections:
                custom_report += """🎯 ENGAGEMENT METRICS
    Total Engagement Points: 124,750
    Average Points per Alumni: 365
    Engagement Growth: +23% vs previous period

    Activity Breakdown:
    • Forum Posts: 234 activities
    • Event Participation: 445 activities
    • Networking: 389 activities
    • Content Creation: 123 activities
    • Career Services: 278 activities

    Top Engaged Alumni:
    1. Sarah Johnson: 1,250 points
    2. Michael Chen: 1,100 points
    3. Dr. Lisa Martinez: 950 points

    """

            if 'events' in selected_sections:
                custom_report += """📅 EVENT STATISTICS
    Total Events: 24
    Total Attendance: 967
    Average Attendance Rate: 66.4%

    Event Types:
    • In-Person: 16 events (76.6% attendance)
    • Virtual: 6 events (52.6% attendance)
    • Hybrid: 2 events (37.4% attendance)

    Popular Event Categories:
    • Professional Development: 8 events
    • Networking: 6 events
    • Industry-Specific: 5 events
    • Social: 3 events
    • Reunion: 2 events

    """

            if 'donations' in selected_sections:
                custom_report += """💰 DONATION ANALYSIS
    Total Donations: £234,750
    Number of Donors: 156
    Average Donation: £1,505
    Donor Participation Rate: 12.5%

    Campaign Performance:
    • Annual Fund: £156,750 (66.8%)
    • Scholarship Fund: £45,600 (19.4%)
    • Building Fund: £23,400 (10.0%)
    • Emergency Fund: £9,000 (3.8%)

    Payment Methods:
    • Credit Card: 66.8%
    • Bank Transfer: 19.4%
    • Check: 10.0%
    • Other: 3.8%

    """

            if 'mentorships' in selected_sections:
                custom_report += """🤝 MENTORSHIP DATA
    Active Mentorships: 15
    Total Mentors: 25
    Total Mentees: 18
    Match Success Rate: 89%

    Focus Areas:
    • Career Planning: 6 mentorships
    • Industry Transition: 4 mentorships
    • Leadership Development: 3 mentorships
    • Technical Skills: 2 mentorships

    Average Mentorship Duration: 8.5 months
    Satisfaction Rating: 4.7/5.0

    """

            if 'geographic' in selected_sections:
                custom_report += """🌍 GEOGRAPHIC DISTRIBUTION
    Domestic Alumni: 1,058 (84.9%)
    International Alumni: 189 (15.1%)

    Top US Locations:
    • San Francisco Bay Area: 234 alumni (18.8%)
    • New York City: 178 alumni (14.3%)
    • Los Angeles: 145 alumni (11.6%)
    • Boston: 123 alumni (9.9%)
    • Chicago: 89 alumni (7.1%)

    International Presence:
    • Canada: 45 alumni (3.6%)
    • United Kingdom: 34 alumni (2.7%)
    • Germany: 23 alumni (1.8%)
    • Australia: 18 alumni (1.4%)
    • Other Countries: 69 alumni (5.5%)

    """

            custom_report += f"""
    ========================================================================================
    Report Configuration:
    • Sections Included: {', '.join([s.replace('_', ' ').title() for s in selected_sections])}
    • Date Range: {self.report_start_date.get()} to {self.report_end_date.get()}
    • Format: {self.report_format.get()}
    • Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

    This custom report has been generated based on your specifications.
    Data reflects the alumni community status as of the report generation date.
    """

            self.report_output.insert(tk.END, custom_report)
            self.update_status(f"Custom report generated with {len(selected_sections)} sections")

        def generate_donation_report(self):
            """Generate donation analysis report"""
            self.report_output.delete(1.0, tk.END)

            donation_report = f"""DONATION ANALYSIS REPORT
    Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
    ========================================

    💰 FINANCIAL OVERVIEW
    Report Period: January 1, 2025 - August 19, 2025
    Total Donations: £234,750
    Number of Donors: 156
    Average Donation: £1,505
    Growth vs. Previous Year: +18%

    📊 DONATION STATISTICS
    Total Transactions: 298
    • One-time donations: 234 (78.5%)
    • Recurring donations: 64 (21.5%)
    • Average transaction: £788

    Donor Participation:
    • Total Alumni: 1,247
    • Donor Rate: 12.5%
    • Repeat Donors: 67 (43.0%)
    • New Donors: 89 (57.0%)

    💵 DONATION RANGES
    £1 - £50: 89 donations (29.9%) - £2,340
    £51 - £100: 67 donations (22.5%) - £5,670
    £101 - £500: 78 donations (26.2%) - £23,450
    £501 - £1,000: 34 donations (11.4%) - £25,600
    £1,001 - £5,000: 23 donations (7.7%) - £67,800
    £5,000+: 7 donations (2.3%) - £109,890

    🎯 CAMPAIGN PERFORMANCE
    Annual Alumni Fund: £156,750 (66.8%)
    • Goal: £100,000 | Achievement: 156.8%
    • Donors: 123
    • Average: £1,275

    Scholarship Fund: £45,600 (19.4%)
    • Goal: £50,000 | Achievement: 91.2%
    • Donors: 34
    • Average: £1,341

    Building Fund: £23,400 (10.0%)
    • Goal: £25,000 | Achievement: 93.6%
    • Donors: 18
    • Average: £1,300

    Emergency Fund: £9,000 (3.8%)
    • Goal: £15,000 | Achievement: 60.0%
    • Donors: 15
    • Average: £600

    📈 MONTHLY TRENDS
    January: £18,450 (67 donations)
    February: £23,670 (45 donations)
    March: £34,560 (89 donations) ← Peak
    April: £28,900 (34 donations)
    May: £31,240 (56 donations)
    June: £25,780 (23 donations)
    July: £29,650 (45 donations)
    August: £42,500 (39 donations) ← Strong finish

    🎓 DONOR DEMOGRAPHICS
    By Graduation Decade:
    • 2020s: £45,600 (19.4%) - 67 donors
    • 2010s: £109,890 (46.8%) - 56 donors
    • 2000s: £67,800 (28.9%) - 23 donors
    • 1990s: £11,460 (4.9%) - 10 donors

    By Industry:
    • Technology: £89,750 (38.2%) - 45 donors
    • Healthcare: £45,600 (19.4%) - 23 donors
    • Finance: £34,560 (14.7%) - 18 donors
    • Education: £23,400 (10.0%) - 12 donors
    • Other: £41,440 (17.7%) - 58 donors

    💳 PAYMENT METHODS
    Credit Card: £156,750 (66.8%)
    Bank Transfer: £45,600 (19.4%)
    Check: £23,400 (10.0%)
    Online Payment: £9,000 (3.8%)

    🔄 RECURRING DONATIONS
    Total Recurring: £67,800 (28.9%)
    Monthly: £34,560 (43 donors)
    Quarterly: £23,400 (18 donors)
    Annual: £9,840 (3 donors)
    Retention Rate: 87%

    🏆 MAJOR DONORS (>£1,000)
    1. Anonymous: £25,000 (Building Fund)
    2. Johnson Family Foundation: £15,000 (Scholarship)
    3. Tech Innovations Inc.: £10,000 (Annual Fund)
    4. Dr. Martinez: £7,500 (Emergency Fund)
    5. Chen Financial Group: £5,000 (Annual Fund)

    📍 GEOGRAPHIC GIVING
    San Francisco Bay Area: £78,900 (33.6%)
    New York Metro: £56,700 (24.2%)
    Los Angeles: £34,200 (14.6%)
    Boston: £23,100 (9.8%)
    International: £18,450 (7.9%)
    Other US: £23,400 (9.9%)

    🎯 INSIGHTS & TRENDS
    Positive Indicators:
    • 18% growth in total giving
    • 23% increase in new donors
    • Strong recurring donation program
    • High donor retention (87%)
    • Successful campaign completion

    Areas for Improvement:
    • Low overall participation rate (12.5%)
    • Limited international giving
    • Emergency fund underperformance
    • Need for major gift cultivation

    📋 RECOMMENDATIONS
    1. Increase donor acquisition targeting
    2. Develop international giving strategy
    3. Launch major gifts program
    4. Enhance emergency fund messaging
    5. Implement peer-to-peer fundraising
    6. Create giving societies/recognition levels
    7. Expand corporate partnership program

    Overall Grade: A- (Strong Performance)
    Fundraising Health: Excellent
    """

            self.report_output.insert(tk.END, donation_report)
            self.update_status("Donation report generated")

        def generate_engagement_report(self):
            """Generate engagement metrics report"""
            self.report_output.delete(1.0, tk.END)

            engagement_report = f"""ALUMNI ENGAGEMENT REPORT
    Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
    =============================================

    📈 ENGAGEMENT OVERVIEW
    Report Period: January 1, 2025 - August 19, 2025
    Total Active Users: 342
    Total Activities: 2,847
    Average Activities per User: 8.3

    🏆 TOP PERFORMERS
    1. Sarah Johnson: 1,250 points (45 activities)
    2. Michael Chen: 1,100 points (38 activities)
    3. Dr. Lisa Martinez: 950 points (32 activities)
    4. Emily Davis: 825 points (28 activities)
    5. John Smith: 750 points (25 activities)

    📊 ACTIVITY BREAKDOWN
    Event Participation: 445 activities (15.6%)
    • Event registrations: 267
    • Event check-ins: 178
    • Average attendance rate: 66.7%

    Forum Engagement: 567 activities (19.9%)
    • Posts created: 234
    • Replies posted: 333
    • Most active category: Career Advice

    Networking Activities: 389 activities (13.7%)
    • Connection requests: 234
    • Connections accepted: 155
    • Average connections per user: 3.2

    Content Contribution: 234 activities (8.2%)
    • Stories submitted: 45
    • Photos uploaded: 123
    • Comments posted: 66

    Career Services: 445 activities (15.6%)
    • Job postings: 67
    • Job applications: 234
    • Mentorship requests: 89
    • Career counseling: 55

    Giving & Donations: 178 activities (6.3%)
    • Donations made: 156
    • Campaign interactions: 22
    • Average donation: £275

    Other Activities: 589 activities (20.7%)
    • Profile updates: 234
    • Directory searches: 189
    • Newsletter opens: 166

    🎯 ENGAGEMENT TRENDS
    Monthly Active Users:
    • January: 234 users
    • February: 245 users
    • March: 267 users
    • April: 289 users
    • May: 298 users
    • June: 312 users
    • July: 334 users
    • August: 342 users

    Growth Rate: +46% year-over-year

    📱 PLATFORM USAGE
    • Web Platform: 67% of activities
    • Mobile App: 28% of activities
    • Email Interactions: 5% of activities

    Peak Usage Times:
    • Tuesday-Thursday: 45% of activities
    • Evening hours (6-9 PM): 38% of activities
    • Weekend mornings: 22% of activities

    🏅 BADGE DISTRIBUTION
    Total Badges Earned: 1,247
    • Community Leader: 23 alumni
    • Super Networker: 67 alumni
    • Career Catalyst: 45 alumni
    • Mentor Master: 34 alumni
    • Generous Donor: 156 alumni

    🎯 ENGAGEMENT INSIGHTS
    High Engagement Factors:
    • Recent graduates (2020+): 34% more active
    • Alumni in tech industry: 28% higher participation
    • Mentors: 45% above average engagement
    • Event attendees: 67% more likely to return

    Low Engagement Segments:
    • Graduates 2000-2010: 45% below average
    • International alumni: 23% lower participation
    • Non-donors: 34% less engaged

    📈 RECOMMENDATIONS
    1. Create targeted campaigns for low-engagement segments
    2. Develop mobile-first features for younger alumni
    3. Expand virtual event offerings for international alumni
    4. Implement gamification for sustained engagement
    5. Create industry-specific content and communities

    Engagement Score: 8.3/10 (Excellent)
    Trend: ↗️ Increasing
    """

            self.report_output.insert(tk.END, engagement_report)
            self.update_status("Engagement report generated")

        def generate_event_report(self):
            """Generate event attendance report"""
            self.report_output.delete(1.0, tk.END)

            event_report = f"""EVENT ATTENDANCE REPORT
    Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
    =====================================

    📅 EVENT OVERVIEW
    Report Period: January 1, 2025 - August 19, 2025
    Total Events: 24
    Total Registrations: 1,456
    Total Attendance: 967
    Average Attendance Rate: 66.4%

    🎯 EVENT PERFORMANCE
    High Attendance Events:
    1. Annual Alumni Gala (Sept 2024): 189/200 (94.5%)
    2. Tech Industry Networking: 87/100 (87.0%)
    3. Healthcare Career Panel: 76/80 (95.0%)
    4. Finance Professionals Mixer: 65/75 (86.7%)
    5. Startup Showcase: 98/120 (81.7%)

    Low Attendance Events:
    1. Virtual Book Club: 12/50 (24.0%)
    2. Arts & Culture Tour: 23/60 (38.3%)
    3. Alumni Golf Tournament: 34/80 (42.5%)

    📊 EVENT TYPES
    In-Person Events: 16 events
    • Registrations: 987
    • Attendance: 756 (76.6%)
    • Average: 47 attendees per event

    Virtual Events: 6 events
    • Registrations: 234
    • Attendance: 123 (52.6%)
    • Average: 21 attendees per event

    Hybrid Events: 2 events
    • Registrations: 235
    • Attendance: 88 (37.4%)
    • Average: 44 attendees per event

    💰 REVENUE EVENTS
    Paid Events: 8 events
    • Total Revenue: £23,450
    • Average Ticket Price: £32
    • Revenue per Attendee: £48

    Free Events: 16 events
    • Registration Rate: 89%
    • Attendance Rate: 71%
    • Higher community engagement

    📈 MONTHLY DISTRIBUTION
    January: 2 events (134 attendees)
    February: 3 events (178 attendees)
    March: 4 events (234 attendees) ← Peak
    April: 2 events (89 attendees)
    May: 3 events (156 attendees)
    June: 4 events (198 attendees)
    July: 3 events (167 attendees)
    August: 3 events (145 attendees)

    🎓 ATTENDEE DEMOGRAPHICS
    By Graduation Year:
    • 2020-2025: 334 attendees (34.5%)
    • 2015-2019: 298 attendees (30.8%)
    • 2010-2014: 234 attendees (24.2%)
    • 2005-2009: 78 attendees (8.1%)
    • Pre-2005: 23 attendees (2.4%)

    By Industry:
    • Technology: 298 attendees (30.8%)
    • Healthcare: 187 attendees (19.3%)
    • Finance: 145 attendees (15.0%)
    • Education: 123 attendees (12.7%)
    • Other: 214 attendees (22.1%)

    🌍 GEOGRAPHIC ATTENDANCE
    Local (within 50 miles): 734 attendees (75.9%)
    Regional (50-200 miles): 145 attendees (15.0%)
    National (200+ miles): 67 attendees (6.9%)
    International: 21 attendees (2.2%)

    📱 REGISTRATION CHANNELS
    Alumni Platform: 567 registrations (38.9%)
    Email Invitations: 445 registrations (30.6%)
    Social Media: 234 registrations (16.1%)
    Word of Mouth: 156 registrations (10.7%)
    Website: 54 registrations (3.7%)

    ⏰ TIMING ANALYSIS
    Best Days: Tuesday, Wednesday, Thursday
    Best Times: 6:00-8:00 PM weekdays
    Weekend Events: 45% lower attendance
    Lunch Events: 67% attendance rate
    Evening Events: 78% attendance rate

    🎯 EVENT SATISFACTION
    Post-Event Surveys (423 responses):
    • Overall Satisfaction: 4.3/5.0
    • Content Quality: 4.2/5.0
    • Networking Value: 4.1/5.0
    • Organization: 4.4/5.0
    • Venue/Platform: 4.0/5.0

    Top Feedback Themes:
    • "Great networking opportunities"
    • "Excellent speakers and content"
    • "Well organized events"
    • "More virtual options needed"
    • "Earlier event announcements requested"

    💡 SUCCESS FACTORS
    High-Performing Events Feature:
    • Industry-specific content (87% avg attendance)
    • Networking opportunities (82% avg attendance)
    • Distinguished speakers (78% avg attendance)
    • Professional development focus (76% avg attendance)
    • Free admission (71% avg attendance)

    📋 RECOMMENDATIONS
    1. Focus on weekday evening events
    2. Increase industry-specific programming
    3. Improve virtual event engagement
    4. Earlier event promotion (4-6 weeks)
    5. Develop speaker bureau from alumni
    6. Create event series for consistency
    7. Enhance hybrid event experience
    8. Implement event reminders system

    Event Program Grade: B+ (Good Performance)
    Attendance Trend: ↗️ Growing
    Community Engagement: Strong
    """

            self.report_output.insert(tk.END, event_report)
            self.update_status("Event report generated")

        def generate_recognition_report_gui(self):
            """Generate recognition report in GUI"""
            self.recognition_report.delete(1.0, tk.END)

            report_content = """DONOR RECOGNITION LEVEL REPORT
        ==============================

        Bronze Supporter: 15 donors (£7,500.00)
        Silver Supporter: 8 donors (£12,000.00)
        Gold Supporter: 5 donors (£15,000.00)
        Platinum Supporter: 2 donors (£18,000.00)
        Diamond Supporter: 1 donor (£15,000.00)
        Benefactor: 0 donors (£0.00)

        ----------------------------------------
        Total: 31 donors (£67,500.00)

        Recent Upgrades:
        - 3 donors upgraded to Silver level this month
        - 1 donor achieved Gold level
        - Recognition ceremony scheduled for next quarter

        Growth Trends:
        - 23% increase in total giving vs. last year
        - Average gift size increased 18%
        - Donor retention rate: 87%
        """

            self.recognition_report.insert(tk.END, report_content)
            self.update_status("Recognition report generated")

        def show_analytics(self):
            """Show system analytics dashboard"""
            self.clear_content()
            self.update_status("System Analytics")

            ttk.Label(self.content_frame, text="Alumni System Analytics",
                     font=('Arial', 16, 'bold')).pack(pady=(0, 20))

            # Analytics tabs
            notebook = ttk.Notebook(self.content_frame)
            notebook.pack(fill=tk.BOTH, expand=True, padx=20, pady=(0, 20))

            # Usage analytics tab
            usage_frame = ttk.Frame(notebook)
            notebook.add(usage_frame, text="Usage Analytics")

            usage_text = ScrolledText(usage_frame, wrap=tk.WORD)
            usage_text.pack(fill=tk.BOTH, expand=True, padx=10, pady=10)

            usage_analytics = f"""SYSTEM USAGE ANALYTICS
    Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
    ======================

    📊 PLATFORM METRICS
    Total Users: 1,247
    Active Users (30 days): 342 (27.4%)
    Daily Active Users: 89 (7.1%)
    Session Duration (avg): 12.3 minutes
    Page Views (monthly): 15,670

    🖥️ DEVICE & BROWSER ANALYTICS
    Device Usage:
    • Desktop: 67.3%
    • Mobile: 28.2%
    • Tablet: 4.5%

    Operating Systems:
    • Windows: 45.6%
    • macOS: 23.4%
    • iOS: 18.9%
    • Android: 12.1%

    Browsers:
    • Chrome: 56.7%
    • Safari: 23.4%
    • Firefox: 12.8%
    • Edge: 7.1%

    📱 PLATFORM ENGAGEMENT
    Page Views by Section:
    • Alumni Directory: 34.2%
    • Job Board: 23.5%
    • Events: 18.7%
    • Forums: 12.3%
    • Mentorship: 8.9%
    • Other: 2.4%

    Average Session Duration by Section:
    • Events: 18.5 minutes
    • Job Board: 15.2 minutes
    • Alumni Directory: 12.8 minutes
    • Forums: 11.4 minutes
    • Mentorship: 9.7 minutes

    ⏰ USAGE PATTERNS
    Peak Usage Times:
    • Tuesday-Thursday: 6-8 PM (45% of traffic)
    • Saturday: 10 AM-12 PM (23% of traffic)
    • Sunday: 2-4 PM (18% of traffic)

    Geographic Distribution:
    • United States: 78.5%
    • Canada: 12.3%
    • United Kingdom: 4.2%
    • Other International: 5.0%

    🔧 TECHNICAL METRICS
    Average Page Load Time: 2.3 seconds
    System Uptime: 99.7%
    Error Rate: 0.03%
    API Response Time: 450ms average

    📈 GROWTH TRENDS
    Month-over-Month Growth:
    • New User Registrations: +12%
    • Daily Active Users: +18%
    • Page Views: +25%
    • Feature Usage: +22%
    """
            usage_text.insert(tk.END, usage_analytics)

            # Performance analytics tab
            performance_frame = ttk.Frame(notebook)
            notebook.add(performance_frame, text="Performance Metrics")

            performance_text = ScrolledText(performance_frame, wrap=tk.WORD)
            performance_text.pack(fill=tk.BOTH, expand=True, padx=10, pady=10)

            performance_analytics = """PERFORMANCE ANALYTICS
    ====================

    🎯 USER ENGAGEMENT METRICS
    Engagement Score (1-10): 7.8
    Monthly Active Users: 342/1,247 (27.4%)
    Weekly Active Users: 189/1,247 (15.2%)
    Daily Active Users: 89/1,247 (7.1%)

    Feature Adoption Rates:
    • Alumni Directory: 78%
    • Event Registration: 45%
    • Job Board: 62%
    • Forum Participation: 34%
    • Mentorship: 15%
    • Donations: 12%

    User Retention:
    • 7-day retention: 45%
    • 30-day retention: 28%
    • 90-day retention: 18%

    📊 CONTENT ENGAGEMENT
    Forum Posts: 234 this month
    • Average comments per post: 3.2
    • Top categories: Career Advice, Networking
    • Most active posters: 12 users (85% of content)

    Event Participation:
    • Average attendance rate: 66.4%
    • Most popular: Professional development events
    • Feedback scores: 4.3/5.0 average

    Job Board Performance:
    • Jobs posted: 67 this year
    • Applications submitted: 234
    • Successful placements: 23 (estimated)

    🔍 USER BEHAVIOR INSIGHTS
    Most Common User Journeys:
    1. Login → Directory Search → Profile View (45%)
    2. Login → Events → Registration (23%)
    3. Login → Job Board → Apply (18%)
    4. Login → Forum → Post/Reply (14%)

    Feature Usage Correlation:
    • Directory users 3x more likely to attend events
    • Job board users 2x more likely to become mentors
    • Forum participants have 40% longer sessions

    💡 OPTIMIZATION OPPORTUNITIES
    • Mobile experience needs improvement (high bounce rate)
    • Forum engagement could be increased with gamification
    • Mentorship program has room for growth
    • International users need better time zone support
    """
            performance_text.insert(tk.END, performance_analytics)

        def show_generate_reports(self):
            """Show report generation interface in a separate window"""
            # Create new Toplevel window for reports
            self.reports_window = tk.Toplevel(self.root)
            self.reports_window.title("Alumni Reports & Analytics")
            self.reports_window.geometry("900x700")
            self.reports_window.transient(self.root)

            # Main frame
            main_frame = ttk.Frame(self.reports_window, padding=10)
            main_frame.pack(fill=tk.BOTH, expand=True)

            ttk.Label(main_frame, text="Alumni Reports & Analytics",
                     font=('Arial', 16, 'bold')).pack(pady=(0, 20))

            # Report types frame
            reports_frame = ttk.LabelFrame(main_frame, text="Available Reports", padding=10)
            reports_frame.pack(fill=tk.X, pady=(0, 20))

            # Quick reports
            quick_frame = ttk.Frame(reports_frame)
            quick_frame.pack(fill=tk.X, pady=(0, 10))

            ttk.Label(quick_frame, text="Quick Reports:", font=('Arial', 10, 'bold')).pack(anchor='w')

            quick_buttons = [
                ("Alumni Summary Report", lambda: self._generate_report_in_window('summary')),
                ("Engagement Report", lambda: self._generate_report_in_window('engagement')),
                ("Donation Summary", lambda: self._generate_report_in_window('donation'))
            ]

            btn_frame = ttk.Frame(quick_frame)
            btn_frame.pack(fill=tk.X, pady=(5, 0))
            for text, command in quick_buttons:
                ttk.Button(btn_frame, text=text, command=command).pack(side=tk.LEFT, padx=(0, 10))

            # Custom report builder
            custom_frame = ttk.LabelFrame(main_frame, text="Custom Report Builder", padding=10)
            custom_frame.pack(fill=tk.BOTH, expand=True, pady=(0, 10))

            # Report parameters
            params_frame = ttk.Frame(custom_frame)
            params_frame.pack(fill=tk.X, pady=(0, 10))

            # Date range
            date_frame = ttk.Frame(params_frame)
            date_frame.pack(fill=tk.X, pady=(0, 10))

            ttk.Label(date_frame, text="Date Range:").pack(side=tk.LEFT, padx=(0, 10))
            self.report_start_date = tk.StringVar(value="2024-01-01")
            ttk.Entry(date_frame, textvariable=self.report_start_date, width=12).pack(side=tk.LEFT, padx=(0, 5))
            ttk.Label(date_frame, text="to").pack(side=tk.LEFT, padx=(0, 5))
            self.report_end_date = tk.StringVar(value="2025-08-19")
            ttk.Entry(date_frame, textvariable=self.report_end_date, width=12).pack(side=tk.LEFT)

            # Report sections
            sections_frame = ttk.Frame(params_frame)
            sections_frame.pack(fill=tk.X, pady=(0, 10))

            ttk.Label(sections_frame, text="Include Sections:").pack(anchor='w')

            self.report_sections = {}
            sections = [
                ("demographics", "Alumni Demographics"),
                ("engagement", "Engagement Metrics"),
                ("events", "Event Statistics"),
                ("donations", "Donation Analysis"),
                ("mentorships", "Mentorship Data"),
                ("geographic", "Geographic Distribution")
            ]

            sections_grid = ttk.Frame(sections_frame)
            sections_grid.pack(fill=tk.X, pady=(5, 0))

            for i, (key, label) in enumerate(sections):
                self.report_sections[key] = tk.BooleanVar(value=True)
                ttk.Checkbutton(sections_grid, text=label,
                               variable=self.report_sections[key]).grid(row=i//2, column=i%2, sticky='w', padx=(0, 20))

            # Generate button
            ttk.Button(params_frame, text="Generate Custom Report",
                      command=lambda: self._generate_report_in_window('custom')).pack(pady=10)

            # Report output area
            output_frame = ttk.LabelFrame(custom_frame, text="Report Output", padding=10)
            output_frame.pack(fill=tk.BOTH, expand=True)

            self.report_output = ScrolledText(output_frame, wrap=tk.WORD)
            self.report_output.pack(fill=tk.BOTH, expand=True)

            # Initial message
            self.report_output.insert(tk.END, "Select a quick report or configure custom report parameters above.\n\n")
            self.report_output.insert(tk.END, "Reports will be displayed here and can be exported.")

            # Action buttons frame (Save and Email)
            action_frame = ttk.Frame(main_frame)
            action_frame.pack(fill=tk.X, pady=(10, 0))

            ttk.Button(action_frame, text="Save Report as TXT",
                      command=self._save_report_as_txt).pack(side=tk.LEFT, padx=(0, 10))
            ttk.Button(action_frame, text="Email Report to Admin",
                      command=self._email_report_to_admin).pack(side=tk.LEFT, padx=(0, 10))
            ttk.Button(action_frame, text="Close",
                      command=self.reports_window.destroy).pack(side=tk.RIGHT)

