"""Centralised filesystem path helpers for the program package.

DEPRECATED: This module has been moved to university_system.core.paths
to prevent circular imports. This file now re-exports everything from core
for backward compatibility.

New code should import from:
    from university_system.core.paths import DEFAULT_DB_PATH, ...

This backward compatibility shim will be removed in a future version.
"""

# Re-export everything from core.paths for backward compatibility
from university_system.core.paths import (
    ANALYTICS_DIR,
    ANALYTICS_PLOTS_DIR,
    ANALYTICS_REPORTS_DIR,
    ASSETS_DIR,
    ASSIGNMENT_TEMPLATES_DIR,
    BACKUP_DIR,
    BACKUP_METADATA_FILE,
    BACKUP_TEMPLATES_DIR,
    BASE_DIR,
    CHARTS_DIR,
    CHATBOT_CONFIG_PATH,
    CHATBOT_DATA_DIR,
    CHATBOT_MODELS_DIR,
    CHATBOT_UPLOAD_DIR,
    CONFIG_DIR,
    DATA_DIR,
    DB_BACKUPS_DIR,
    DB_DIR,
    DB_EXPORTS_DIR,
    DB_FILES_DIR,
    DEFAULT_DB_PATH,
    EMAIL_CONFIG_FILE,
    EMAIL_CONFIG_PATH,
    EMAIL_DATA_DIR,
    EMAIL_REMINDER_TEMPLATES_DIR,
    EMAIL_TEMPLATES_DIR,
    EXPORTS_DIR,
    FINANCE_TEMPLATES_DIR,
    LANGUAGE_CONFIG_PATH,
    LOCALES_DIR,
    LOG_DIR,
    LOGGER_CONFIG_DIR,
    MEDICAL_TEMPLATES_DIR,
    NLTK_DATA_DIR,
    PROJECT_ROOT,
    QR_CODES_DIR,
    REPO_ROOT,
    REPORT_CACHE_DIR,
    REPORT_TEMPLATES_DIR,
    REPORTS_DIR,
    SCRIPTS_DIR,
    SRC_DIR,
    STUDENT_DOCUMENTS_DIR,
    SUBMISSIONS_DIR,
    TEMP_DIR,
    TEMPLATES_DIR,
    TICKET_TEMPLATES_DIR,
    UNIVERSITY_SYSTEM_DIR,
    UPLOAD_DIR,
    UPLOADS_DIR,
    ensure_directories,
)

__all__ = [
    "BASE_DIR",
    "UNIVERSITY_SYSTEM_DIR",
    "PROJECT_ROOT",
    "REPO_ROOT",
    "SRC_DIR",
    "DATA_DIR",
    "DB_DIR",
    "DB_FILES_DIR",
    "DB_EXPORTS_DIR",
    "DEFAULT_DB_PATH",
    "DB_BACKUPS_DIR",
    "BACKUP_METADATA_FILE",
    "LOG_DIR",
    "BACKUP_DIR",
    "REPORTS_DIR",
    "REPORT_TEMPLATES_DIR",
    "REPORT_CACHE_DIR",
    "EMAIL_DATA_DIR",
    "EMAIL_CONFIG_PATH",
    "EMAIL_TEMPLATES_DIR",
    "CONFIG_DIR",
    "EMAIL_CONFIG_FILE",
    "LOGGER_CONFIG_DIR",
    "CHATBOT_DATA_DIR",
    "CHATBOT_UPLOAD_DIR",
    "CHATBOT_MODELS_DIR",
    "CHATBOT_CONFIG_PATH",
    "QR_CODES_DIR",
    "ANALYTICS_DIR",
    "ANALYTICS_PLOTS_DIR",
    "ANALYTICS_REPORTS_DIR",
    "SUBMISSIONS_DIR",
    "UPLOAD_DIR",
    "UPLOADS_DIR",
    "TEMP_DIR",
    "TEMPLATES_DIR",
    "ASSIGNMENT_TEMPLATES_DIR",
    "BACKUP_TEMPLATES_DIR",
    "MEDICAL_TEMPLATES_DIR",
    "TICKET_TEMPLATES_DIR",
    "EMAIL_REMINDER_TEMPLATES_DIR",
    "FINANCE_TEMPLATES_DIR",
    "NLTK_DATA_DIR",
    "STUDENT_DOCUMENTS_DIR",
    "EXPORTS_DIR",
    "CHARTS_DIR",
    "LOCALES_DIR",
    "LANGUAGE_CONFIG_PATH",
    "ASSETS_DIR",
    "SCRIPTS_DIR",
    "ensure_directories",
]
