# Re-exports for backward compatibility
from education_system.post_18.university_system.modules.domain.finance.gui.finance_reporting.main import (
    FinancialManagementGUI,
    set_auth,
)

# Export standalone functions from misc
from education_system.post_18.university_system.modules.domain.finance.gui.finance_reporting.misc import (
    launch_financial_gui,
    display_finance_menu,
    financial_dashboard,
    generate_financial_forecasting,
    generate_budget_variance_report,
    generate_advanced_financial_forecasting,
    generate_comprehensive_budget_variance_report,
    real_time_financial_dashboard,
    automated_reporting_system,
    scenario_planning_tools,
    advanced_export_system,
    compliance_audit_system,
    get_current_academic_year,
    initialize_enhanced_database,
    run_system_health_check,
    backup_database,
    clean_database,
    show_database_stats,
    initialize_database,
    update_exchange_rates,
    test_email_service,
    save_general_settings,
    display_enhanced_finance_menu,
    display_enhanced_finance_menu_console,
    test_auth_integration,
    demo_auth_integration,
    ensure_financial_alerts_table,
    init_enhanced_finance_db,
    generate_revenue_summary,
    generate_student_financial_summary,
    view_overdue_accounts,
    analyze_payment_patterns,
    collection_performance_summary,
    aid_distribution_summary,
    budget_summary_report,
    generate_comprehensive_forecast_report,
    track_collection_progress,
    review_pending_aid_applications,
    track_loan_repayments,
    budget_vs_actual_analysis,
    budget_approval_workflow,
    generate_revenue_forecast,
    generate_enrollment_projections,
    generate_cash_flow_analysis,
    generate_risk_analysis,
    scholarship_distribution_summary,
    student_scholarship_report,
    scholarship_utilization_analysis,
    bulk_assign_fees_to_course,
    calculate_late_fees,
    generate_predictive_analytics,
    detect_payment_fraud,
)

# Export dialog classes
from education_system.post_18.university_system.modules.domain.finance.gui.finance_reporting.payment_dialogs import (
    PaymentDialog,
    RefundDialog,
    FeeTypeDialog,
    AssignFeeDialog,
    PaymentDetailsDialog,
)

from education_system.post_18.university_system.modules.domain.finance.gui.finance_reporting.student_dialogs import (
    StudentDialog,
    StudentFinancesDialog,
    CollectionCaseDialog,
    CollectionAgenciesDialog,
)

from education_system.post_18.university_system.modules.domain.finance.gui.finance_reporting.aid_budget_dialogs import (
    AidApplicationDialog,
    AidDisbursementDialog,
    BudgetPlanDialog,
)

# Export analytics classes
from education_system.post_18.university_system.modules.domain.finance.gui.finance_reporting.analytics_classes import (
    FinancialAlertSystem,
    PaymentPredictionML,
    AnomalyDetector,
    CashFlowForecaster,
    StudentLifecycleAnalyzer,
    ComparativeAnalyzer,
)

__all__ = [
    'FinancialManagementGUI',
    'set_auth',
    'launch_financial_gui',
    'display_finance_menu',
    'financial_dashboard',
    'generate_financial_forecasting',
    'generate_budget_variance_report',
    'generate_advanced_financial_forecasting',
    'generate_comprehensive_budget_variance_report',
    'real_time_financial_dashboard',
    'automated_reporting_system',
    'scenario_planning_tools',
    'advanced_export_system',
    'compliance_audit_system',
    'get_current_academic_year',
    'initialize_enhanced_database',
    'run_system_health_check',
    'backup_database',
    'clean_database',
    'show_database_stats',
    'initialize_database',
    'update_exchange_rates',
    'test_email_service',
    'save_general_settings',
    'display_enhanced_finance_menu',
    'display_enhanced_finance_menu_console',
    'test_auth_integration',
    'demo_auth_integration',
    'ensure_financial_alerts_table',
    'init_enhanced_finance_db',
    'generate_revenue_summary',
    'generate_student_financial_summary',
    'view_overdue_accounts',
    'analyze_payment_patterns',
    'collection_performance_summary',
    'aid_distribution_summary',
    'budget_summary_report',
    'generate_comprehensive_forecast_report',
    'track_collection_progress',
    'review_pending_aid_applications',
    'track_loan_repayments',
    'budget_vs_actual_analysis',
    'budget_approval_workflow',
    'generate_revenue_forecast',
    'generate_enrollment_projections',
    'generate_cash_flow_analysis',
    'generate_risk_analysis',
    'scholarship_distribution_summary',
    'student_scholarship_report',
    'scholarship_utilization_analysis',
    'bulk_assign_fees_to_course',
    'calculate_late_fees',
    'generate_predictive_analytics',
    'detect_payment_fraud',
    'PaymentDialog',
    'RefundDialog',
    'FeeTypeDialog',
    'AssignFeeDialog',
    'PaymentDetailsDialog',
    'StudentDialog',
    'StudentFinancesDialog',
    'CollectionCaseDialog',
    'CollectionAgenciesDialog',
    'AidApplicationDialog',
    'AidDisbursementDialog',
    'BudgetPlanDialog',
    'FinancialAlertSystem',
    'PaymentPredictionML',
    'AnomalyDetector',
    'CashFlowForecaster',
    'StudentLifecycleAnalyzer',
    'ComparativeAnalyzer',
]
