"""
Report generation for support analytics.
"""

import datetime
import json
import logging
import time
import re
import os
import hashlib
import mimetypes
import base64
import secrets
import traceback
from typing import Optional, List, Dict, Any
from functools import wraps

from education_system.university_system.infrastructure.database.db import get_connection, sqlite3, DatabaseManager
from education_system.university_system.infrastructure.email.email_manager import send_email
from education_system.university_system.modules.shared.constants.paths import DEFAULT_DB_PATH, TICKET_TEMPLATES_DIR, UPLOAD_DIR
from education_system.university_system.utils.logging.log_config import get_log_file

from ..config import (
    SUPPORT_DB, TICKET_STATUSES, TICKET_PRIORITIES, SUPPORT_CATEGORIES,
    NotificationType, TicketSentiment, FileType, SupportConfig
)
from .. import auth as _auth_mod
from ..auth import get_current_user_safe, require_auth, has_staff_permissions

logger = logging.getLogger(__name__)

def generate_reports(report_type, date_range, filters=None):
    """Generate various types of reports"""
    if not _auth_mod.auth or not _auth_mod.auth.current_user or _auth_mod.auth.current_user['role'] not in ('staff', 'admin'):
        raise PermissionError("You must be staff or admin to generate reports")
    
    try:
        conn = sqlite3.connect(SUPPORT_DB)
        cursor = conn.cursor()
        
        report_data = {}
        
        if report_type == 'ticket_summary':
            report_data = _generate_ticket_summary_report(cursor, date_range, filters)
        elif report_type == 'performance':
            report_data = _generate_performance_report(cursor, date_range, filters)
        elif report_type == 'satisfaction':
            report_data = _generate_satisfaction_report(cursor, date_range, filters)
        elif report_type == 'category_analysis':
            report_data = _generate_category_analysis_report(cursor, date_range, filters)
        
        conn.close()
        
        # Record report generation
        _log_report_generation(report_type, _auth_mod.auth.current_user['id'])
        
        logger.info(f"Report '{report_type}' generated by {_auth_mod.auth.current_user['username']}")
        return report_data
        
    except Exception as e:
        logger.error(f"Error generating report: {e}")
        raise

def _generate_ticket_summary_report(cursor, date_range, filters):
    """Generate ticket summary report"""
    date_params = (date_range['start'], date_range['end'])

    # Total tickets
    cursor.execute('SELECT COUNT(*) FROM support_tickets WHERE created_datetime BETWEEN ? AND ?', date_params)
    total_tickets = cursor.fetchone()[0]

    # Tickets by status
    cursor.execute('SELECT status, COUNT(*) FROM support_tickets WHERE created_datetime BETWEEN ? AND ? GROUP BY status', date_params)
    status_breakdown = dict(cursor.fetchall())

    # Tickets by category
    cursor.execute('SELECT category, COUNT(*) FROM support_tickets WHERE created_datetime BETWEEN ? AND ? GROUP BY category', date_params)
    category_breakdown = dict(cursor.fetchall())

    # Tickets by priority
    cursor.execute('SELECT priority, COUNT(*) FROM support_tickets WHERE created_datetime BETWEEN ? AND ? GROUP BY priority', date_params)
    priority_breakdown = dict(cursor.fetchall())

    # Daily ticket creation
    cursor.execute('''
    SELECT DATE(created_datetime) as date, COUNT(*) as count
    FROM support_tickets
    WHERE created_datetime BETWEEN ? AND ?
    GROUP BY DATE(created_datetime)
    ORDER BY date
    ''', date_params)
    daily_creation = [{'date': row[0], 'count': row[1]} for row in cursor.fetchall()]
    
    return {
        'total_tickets': total_tickets,
        'status_breakdown': status_breakdown,
        'category_breakdown': category_breakdown,
        'priority_breakdown': priority_breakdown,
        'daily_creation': daily_creation,
        'date_range': date_range
    }

def _generate_performance_report(cursor, date_range, filters):
    """Generate performance metrics report"""
    date_params = (date_range['start'], date_range['end'])

    # Resolution time statistics
    cursor.execute('''
    SELECT
        AVG(julianday(resolved_at) - julianday(created_datetime)) * 24 as avg_hours,
        MIN(julianday(resolved_at) - julianday(created_datetime)) * 24 as min_hours,
        MAX(julianday(resolved_at) - julianday(created_datetime)) * 24 as max_hours,
        COUNT(*) as resolved_count
    FROM support_tickets
    WHERE created_datetime BETWEEN ? AND ? AND resolved_at IS NOT NULL
    ''', date_params)

    resolution_stats = cursor.fetchone()

    # Staff performance
    cursor.execute('''
    SELECT
        assigned_to,
        COUNT(*) as total_assigned,
        COUNT(CASE WHEN status = 'Resolved' THEN 1 END) as resolved,
        AVG(CASE WHEN resolved_at IS NOT NULL
            THEN julianday(resolved_at) - julianday(created_datetime)
            END) * 24 as avg_resolution_hours
    FROM support_tickets
    WHERE created_datetime BETWEEN ? AND ? AND assigned_to IS NOT NULL
    GROUP BY assigned_to
    ''', date_params)
    
    staff_performance = [
        {
            'staff_member': row[0],
            'total_assigned': row[1],
            'resolved': row[2],
            'resolution_rate': round(row[2] / row[1] * 100, 1) if row[1] > 0 else 0,
            'avg_resolution_hours': round(row[3] or 0, 1)
        }
        for row in cursor.fetchall()
    ]
    
    return {
        'resolution_stats': {
            'avg_hours': round(resolution_stats[0] or 0, 1),
            'min_hours': round(resolution_stats[1] or 0, 1),
            'max_hours': round(resolution_stats[2] or 0, 1),
            'resolved_count': resolution_stats[3]
        },
        'staff_performance': staff_performance,
        'date_range': date_range
    }

def _generate_satisfaction_report(cursor, date_range, filters):
    """Generate satisfaction survey report"""
    date_params = (date_range['start'], date_range['end'])

    # Average satisfaction rating
    cursor.execute('''
    SELECT
        AVG(satisfaction_rating) as avg_rating,
        COUNT(satisfaction_rating) as response_count,
        COUNT(*) as total_resolved
    FROM support_tickets
    WHERE resolved_at BETWEEN ? AND ? AND satisfaction_rating IS NOT NULL
    ''', date_params)

    satisfaction_data = cursor.fetchone()

    # Rating distribution
    cursor.execute('''
    SELECT satisfaction_rating, COUNT(*)
    FROM support_tickets
    WHERE resolved_at BETWEEN ? AND ? AND satisfaction_rating IS NOT NULL
    GROUP BY satisfaction_rating
    ORDER BY satisfaction_rating
    ''', date_params)
    
    rating_distribution = dict(cursor.fetchall())
    
    return {
        'avg_rating': round(satisfaction_data[0] or 0, 2),
        'response_rate': round(satisfaction_data[1] / max(satisfaction_data[2], 1) * 100, 1),
        'total_responses': satisfaction_data[1],
        'rating_distribution': rating_distribution,
        'date_range': date_range
    }

def _generate_category_analysis_report(cursor, date_range, filters):
    """Generate category analysis report"""
    date_params = (date_range['start'], date_range['end'])

    # Category statistics
    cursor.execute('''
    SELECT
        category,
        COUNT(*) as total_tickets,
        COUNT(CASE WHEN status = 'Resolved' THEN 1 END) as resolved,
        AVG(CASE WHEN resolved_at IS NOT NULL
            THEN julianday(resolved_at) - julianday(created_datetime)
            END) * 24 as avg_resolution_hours,
        AVG(satisfaction_rating) as avg_satisfaction
    FROM support_tickets
    WHERE created_datetime BETWEEN ? AND ?
    GROUP BY category
    ORDER BY total_tickets DESC
    ''', date_params)
    
    category_stats = [
        {
            'category': row[0],
            'total_tickets': row[1],
            'resolved': row[2],
            'resolution_rate': round(row[2] / row[1] * 100, 1) if row[1] > 0 else 0,
            'avg_resolution_hours': round(row[3] or 0, 1),
            'avg_satisfaction': round(row[4] or 0, 2)
        }
        for row in cursor.fetchall()
    ]
    
    return {
        'category_stats': category_stats,
        'date_range': date_range
    }

def _log_report_generation(report_type, user_id):
    """Log report generation for audit"""
    try:
        conn = sqlite3.connect(SUPPORT_DB)
        cursor = conn.cursor()
        
        cursor.execute('''
        INSERT INTO system_metrics (
            metric_name, metric_value, category, recorded_datetime, metadata
        ) VALUES (?, ?, ?, ?, ?)
        ''', (
            'report_generated', 1, 'reports', 
            datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S'),
            json.dumps({'report_type': report_type, 'user_id': user_id})
        ))
        
        conn.commit()
        conn.close()
        
    except Exception as e:
        logger.error(f"Error logging report generation: {e}")

def generate_reports_menu(support):
    """Generate reports menu"""
    try:
        print("\n📊 GENERATE REPORTS")
        print("="*40)
        print("1. Ticket Summary Report")
        print("2. Performance Report")
        print("3. Satisfaction Report")
        print("4. Category Analysis Report")
        print("5. Back")
        
        choice = input("\nSelect report type: ").strip()
        
        if choice == '5':
            return
        
        report_types = {
            '1': 'ticket_summary',
            '2': 'performance',
            '3': 'satisfaction',
            '4': 'category_analysis'
        }
        
        report_type = report_types.get(choice)
        if not report_type:
            print("❌ Invalid choice.")
            return
        
        # Date range
        print("\nDate Range:")
        start_date = input("Start date (YYYY-MM-DD) [30 days ago]: ").strip()
        if not start_date:
            start_date = (datetime.datetime.now() - datetime.timedelta(days=30)).strftime('%Y-%m-%d')
        
        end_date = input("End date (YYYY-MM-DD) [today]: ").strip()
        if not end_date:
            end_date = datetime.datetime.now().strftime('%Y-%m-%d')
        
        date_range = {'start': start_date, 'end': end_date}
        
        print(f"\n📈 Generating {report_type} report...")
        report_data = support.generate_reports(report_type, date_range)
        
        # Display report summary
        print(f"\n📋 REPORT: {report_type.upper()}")
        print("="*50)
        
        if report_type == 'ticket_summary':
            print(f"📊 Total Tickets: {report_data['total_tickets']}")
            print(f"📈 Status Breakdown: {report_data['status_breakdown']}")
            print(f"📁 Category Breakdown: {report_data['category_breakdown']}")
        
        elif report_type == 'performance':
            stats = report_data['resolution_stats']
            print(f"⏱️ Average Resolution Time: {stats['avg_hours']} hours")
            print(f"✅ Resolved Tickets: {stats['resolved_count']}")
            print(f"👥 Staff Performance: {len(report_data['staff_performance'])} staff members")
        
        elif report_type == 'satisfaction':
            print(f"⭐ Average Rating: {report_data['avg_rating']}/5")
            print(f"📊 Response Rate: {report_data['response_rate']}%")
            print(f"📝 Total Responses: {report_data['total_responses']}")
        
        # Export option
        export_choice = input("\nExport report? (y/n): ").lower()
        if export_choice == 'y':
            filename = f"{report_type}_report_{start_date}_to_{end_date}.json"
            with open(filename, 'w') as f:
                json.dump(report_data, f, indent=2)
            print(f"✅ Report exported to {filename}")
    
    except Exception as e:
        print(f"❌ Error generating report: {e}")
    
    input("\nPress Enter to continue...")
