from education_system.university_system.modules.domain.academics.gui.plagiarism_main_gui.main_gui import PlagiarismCheckerGUI
from education_system.university_system.modules.domain.academics.gui.plagiarism_main_gui.config import GuiConfig
from education_system.university_system.modules.domain.academics.gui.plagiarism_main_gui.common import (
    StatusBar,
    ScrollableFrame,
    ResultCard,
    SetupTestingDialog,
    get_authenticated_user_auth,
    get_safe_db_connection,
    download_nltk_data,
    safe_input,
    check_requirements,
    check_database,
    create_directories,
    create_ai_education_content,
    create_sample_documents,
    logger,
    PlagiarismChecker,
    PlagiarismCheckerError,
    DatabaseError,
    FileProcessingError,
    IntegrationError,
    PLAGIARISM_BACKEND_AVAILABLE,
    PLAGIARISM_IMPORT_ERROR,
    NLTK_AVAILABLE,
    TEXTRACT_AVAILABLE,
)
from education_system.university_system.modules.domain.academics.gui.plagiarism_main_gui.launcher import (
    integrate_plagiarism_checker_with_main,
    launch_gui_from_main_system,
    run_gui_standalone,
    run_gui_tests,
    main,
)
from education_system.university_system.modules.domain.academics.gui.plagiarism_main_gui.dialogs import (
    DocumentSubmissionDialog,
    PlagiarismCheckDialog,
    DocumentComparisonDialog,
    CheckResultDialog,
    ResultDetailsDialog,
    StatisticsDialog,
    RepositorySearchDialog,
    AdvancedRepositorySearchDialog,
    DocumentDetailsDialog,
    BulkOperationsDialog,
    DocumentWorkflowDialog,
    FileFormatConverterDialog,
    BackupRestoreDialog,
    SystemTestingDialog,
)

__all__ = [
    'PlagiarismCheckerGUI',
    'GuiConfig',
    'StatusBar',
    'ScrollableFrame',
    'ResultCard',
    'SetupTestingDialog',
    'DocumentSubmissionDialog',
    'PlagiarismCheckDialog',
    'DocumentComparisonDialog',
    'CheckResultDialog',
    'ResultDetailsDialog',
    'StatisticsDialog',
    'RepositorySearchDialog',
    'AdvancedRepositorySearchDialog',
    'DocumentDetailsDialog',
    'BulkOperationsDialog',
    'DocumentWorkflowDialog',
    'FileFormatConverterDialog',
    'BackupRestoreDialog',
    'SystemTestingDialog',
    'integrate_plagiarism_checker_with_main',
    'launch_gui_from_main_system',
    'run_gui_standalone',
    'run_gui_tests',
    'main',
]
