"""
Core package for University Management System.

This package contains shared primitives and fundamental components that
both infrastructure and modules depend on. It has no dependencies on
either infrastructure or modules, preventing circular imports.

Contents:
    - exceptions: Custom exception hierarchy
    - paths: Centralized file path definitions
    - defaults: System default values
    - i18n: Internationalization support
    - sql_safety: SQL identifier validation
    - activity_logger: Centralized activity logging
    - institution_settings: Institution contact configuration
    - logs: Logging utilities
"""

from university_system.core.exceptions import (
    AlreadyEnrolledError,
    AttachmentError,
    AuthenticationError,
    CapacityExceededError,
    ConfigurationError,
    CourseError,
    CourseFullError,
    CourseNotFoundError,
    DatabaseConnectionError,
    DatabaseError,
    DuplicateStudentError,
    EmailDeliveryError,
    EmailError,
    EnrollmentClosedError,
    EnrollmentError,
    FileError,
    FileUploadError,
    FileValidationError,
    FinanceError,
    FormatError,
    GradeError,
    GradeNotFoundError,
    InsufficientFundsError,
    IntegrityError,
    InvalidConfigError,
    InvalidCredentialsError,
    InvalidGradeError,
    InvalidInputError,
    MFARequiredError,
    MissingConfigError,
    MissingFieldError,
    PaymentError,
    PermissionDeniedError,
    PrerequisiteError,
    QueryError,
    SessionExpiredError,
    StudentEnrollmentError,
    StudentError,
    StudentNotFoundError,
    TemplateError,
    TransactionError,
    TransactionFailedError,
    UniversityFileNotFoundError,
    UniversitySystemError,
    ValidationError,
)
from university_system.core.paths import (
    ASSETS_DIR,
    BACKUP_METADATA_FILE,
    BASE_DIR,
    CONFIG_DIR,
    DATA_DIR,
    DB_BACKUPS_DIR,
    DB_DIR,
    DB_EXPORTS_DIR,
    DB_FILES_DIR,
    DEFAULT_DB_PATH,
    EMAIL_CONFIG_FILE,
    EMAIL_TEMPLATES_DIR,
    FINANCE_TEMPLATES_DIR,
    LOCALES_DIR,
    LOG_DIR,
    REPORTS_DIR,
    SCRIPTS_DIR,
    TEMP_DIR,
    TEMPLATES_DIR,
    UNIVERSITY_SYSTEM_DIR,
    UPLOADS_DIR,
)

__all__ = [
    # Exceptions
    'UniversitySystemError',
    'DatabaseError',
    'DatabaseConnectionError',
    'QueryError',
    'TransactionError',
    'IntegrityError',
    'AuthenticationError',
    'InvalidCredentialsError',
    'SessionExpiredError',
    'PermissionDeniedError',
    'MFARequiredError',
    'ValidationError',
    'InvalidInputError',
    'MissingFieldError',
    'FormatError',
    'StudentError',
    'StudentNotFoundError',
    'DuplicateStudentError',
    'StudentEnrollmentError',
    'CourseError',
    'CourseNotFoundError',
    'CourseFullError',
    'PrerequisiteError',
    'EnrollmentError',
    'AlreadyEnrolledError',
    'EnrollmentClosedError',
    'CapacityExceededError',
    'GradeError',
    'InvalidGradeError',
    'GradeNotFoundError',
    'FinanceError',
    'PaymentError',
    'InsufficientFundsError',
    'TransactionFailedError',
    'EmailError',
    'EmailDeliveryError',
    'TemplateError',
    'AttachmentError',
    'FileError',
    'UniversityFileNotFoundError',
    'FileUploadError',
    'FileValidationError',
    'ConfigurationError',
    'MissingConfigError',
    'InvalidConfigError',
    # Paths
    'BASE_DIR',
    'UNIVERSITY_SYSTEM_DIR',
    'DATA_DIR',
    'DB_DIR',
    'DB_FILES_DIR',
    'DEFAULT_DB_PATH',
    'DB_EXPORTS_DIR',
    'DB_BACKUPS_DIR',
    'BACKUP_METADATA_FILE',
    'CONFIG_DIR',
    'EMAIL_CONFIG_FILE',
    'LOG_DIR',
    'REPORTS_DIR',
    'UPLOADS_DIR',
    'TEMP_DIR',
    'TEMPLATES_DIR',
    'EMAIL_TEMPLATES_DIR',
    'FINANCE_TEMPLATES_DIR',
    'LOCALES_DIR',
    'ASSETS_DIR',
    'SCRIPTS_DIR',
]
