"""Operations module for backup data operations."""
from education_system.university_system.modules.shared.gui.database.operations.backup_ops import (
    _cleanup_temp_paths,
    _prepare_backup_for_read,
    _get_table_snapshot,
    _create_incremental_backup_impl,
    _create_differential_backup_impl,
    create_incremental_backup,
    create_enhanced_backup,
    create_selective_backup,
    create_schema_only_backup,
    create_differential_backup,
    compare_backups,
    generate_advanced_statistics,
    get_database_tables,
    get_database_tables_from_connection,
    has_database_changed,
    calculate_file_hash,
    compress_file,
    decompress_file,
    encrypt_file,
    decrypt_file,
    generate_encryption_key,
    secure_delete_file,
    verify_backup_integrity,
    ensure_backup_directory,
    upload_to_aws_s3,
    download_from_aws_s3,
    upload_to_ftp,
    upload_to_sftp,
    cleanup_old_backups,
    notify_backup_result,
    send_email_notification,
    send_slack_notification,
    send_discord_notification,
    validate_backup,
    validate_backup_detailed,
    list_available_backups,
    check_storage_quota,
    deduplicate_backups,
    enable_backup_deduplication,
    cleanup_old_backups_enhanced,
    compare_table_data,
)
from education_system.university_system.modules.shared.gui.database.operations.restore_ops import (
    restore_from_backup,
    restore_partial_tables,
)
from education_system.university_system.modules.shared.gui.database.operations.export_ops import (
    export_to_csv,
    export_to_json,
    export_to_xml,
    export_to_pdf,
    export_to_txt,
)
from education_system.university_system.modules.shared.gui.database.operations.template_ops import (
    list_backup_templates,
    save_backup_template,
    load_backup_template,
)
from education_system.university_system.modules.shared.gui.database.operations.stats_ops import (
    generate_backup_statistics,
    get_log_file,
)
