from education_system.university_system.modules.domain.academics.gui.module_scheduling.main_gui import ModuleSchedulingGUI, main, launch_gui, launch_cli, create_desktop_shortcut, setup_application, launch_module_scheduling_gui, run_gui_with_database

# Import all tab modules to attach methods to ModuleSchedulingGUI
from education_system.university_system.modules.domain.academics.gui.module_scheduling import dashboard_tab
from education_system.university_system.modules.domain.academics.gui.module_scheduling import schedules_tab
from education_system.university_system.modules.domain.academics.gui.module_scheduling import rooms_tab
from education_system.university_system.modules.domain.academics.gui.module_scheduling import instructors_tab
from education_system.university_system.modules.domain.academics.gui.module_scheduling import timetables_tab
from education_system.university_system.modules.domain.academics.gui.module_scheduling import analytics_tab
from education_system.university_system.modules.domain.academics.gui.module_scheduling import conflicts_tab
from education_system.university_system.modules.domain.academics.gui.module_scheduling import management_tab
from education_system.university_system.modules.domain.academics.gui.module_scheduling import settings_tab
from education_system.university_system.modules.domain.academics.gui.module_scheduling import modules_tab
from education_system.university_system.modules.domain.academics.gui.module_scheduling import scheduling_engine
from education_system.university_system.modules.domain.academics.gui.module_scheduling import notifications
from education_system.university_system.modules.domain.academics.gui.module_scheduling import exports
from education_system.university_system.modules.domain.academics.gui.module_scheduling import dialogs
from education_system.university_system.modules.domain.academics.gui.module_scheduling import backup
from education_system.university_system.modules.domain.academics.gui.module_scheduling import misc
