"""Backwards-compatible shim for student union miscellaneous helpers."""

from __future__ import annotations

# This module re-exports everything from the student_union_misc package
# Import specific items as needed
from university_system.modules.domain.student_affairs.student_union.services.union_context import (
    auth,
    check_and_award_badges,
    display_admin_menu,
    display_club_menu,
    display_election_menu,
    display_event_menu,
    display_facility_menu,
    election_accessibility_features,
    election_security_audit,
    engagement_trend_analysis,
    event_popularity_predictions,
    export_voting_configuration,
    generate_advanced_analytics,
    generate_environmental_reports,
    generate_support_reports,
    import_voting_configuration,
    knowledge_sharing_sessions,
    learning_analytics_dashboard,
    manage_academic_support,
    manage_book_clubs,
    manage_community_engagement,
    manage_engagement_rewards,
    manage_enhanced_voting,
    manage_equipment_system,
    manage_green_initiatives,
    manage_interclub_competitions,
    manage_learning_integration,
    manage_mentorship_system,
    manage_peer_support_system,
    manage_shared_resources,
    manage_support_groups_admin,
    manage_sustainable_events,
    manage_virtual_events,
    member_retention_insights,
    monitor_campaign_compliance,
    nominate_for_election,
    set_up_election,
    submit_campaign_materials,
    track_campaign_expenses,
    view_candidate_profiles,
    view_election_results,
    view_elections,
    view_elections_with_campaigns,
    vote_in_election,
)
