from education_system.university_system.infrastructure.database.db import sqlite3, get_connection
from datetime import datetime
import logging

logger = logging.getLogger(__name__)


def escalate_ticket_manual(auth, ticket_id):
    """Manually escalate a ticket"""
    if not auth or not auth.current_user:
        print("You must be logged in to escalate tickets.")
        return

    if not auth.check_permission('manage_tickets'):
        print("You don't have permission to escalate tickets.")
        return

    reason = input("Escalation reason: ").strip()
    if not reason:
        reason = "Manual escalation"

    from education_system.university_system.modules.domain.student_affairs.services.helpdesk.workflows import escalate_ticket
    escalate_ticket(ticket_id, reason)
    print(f"Ticket #{ticket_id} escalated successfully.")

def send_satisfaction_survey(ticket_id):
    """Send customer satisfaction survey"""
    conn = get_connection()
    cursor = conn.cursor()

    # Get ticket and customer info
    cursor.execute('''
    SELECT t.subject, u.username, u.email
    FROM support_tickets t
    JOIN users u ON t.user_id = u.id
    WHERE t.ticket_id = ?
    ''', (ticket_id,))

    ticket_info = cursor.fetchone()

    if ticket_info:
        try:
            # This would integrate with your email system
            print(f"Satisfaction survey sent to {ticket_info[1]} ({ticket_info[2]})")
            # send_satisfaction_survey_email(ticket_id, ticket_info[2], ticket_info[0])
        except Exception as e:
            print(f"Error sending satisfaction survey: {e}")

    conn.close()

def save_report_to_file(report_type, period, auth):
    """Save report data to file"""
    try:
        from education_system.university_system.modules.shared.constants import paths
        timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
        filename = str(paths.REPORTS_DIR / f"{report_type}_{period}_{timestamp}.txt")

        # This would contain the actual report generation logic
        with open(filename, 'w') as f:
            f.write(f"Helpdesk Report: {report_type}\n")
            f.write(f"Period: {period}\n")
            f.write(f"Generated by: {auth.current_user['username']}\n")
            f.write(f"Generated at: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
            f.write("\n" + "="*50 + "\n\n")
            f.write("Report data would go here...\n")

        print(f"Report saved to {filename}")

    except Exception as e:
        print(f"Error saving report: {e}")
