"""Modularised helpers previously grouped in finance.core.miscellaneous."""

from __future__ import annotations

from university_system.modules.domain.finance.finance_misc.finance_context import set_auth
from university_system.modules.domain.finance.finance_misc.finance_db_operations import (
    check_required_packages,
    complete_database_fix,
    ensure_database_exists,
    init_default_enhanced_data,
    init_enhanced_finance_db,
    initialize_finance,
    quick_fix_database,
    verify_fix,
)
from university_system.modules.domain.finance.finance_misc.students import (
    add_student_credit,
    api_get_student_financial_summary,
    apply_credit_to_fees,
    create_sample_students,
    get_student_email,
    get_student_name,
    get_student_phone,
    student_exists,
    view_credit_history,
    view_student_credits,
)
from university_system.modules.domain.finance.finance_misc.communications import (
    send_arrangement_confirmation,
    send_email_aws_ses,
    send_email_sendgrid,
    send_email_smtp,
    send_sms_aws_sns,
    send_sms_twilio,
    setup_email_config,
    setup_sms_config,
    test_email_service,
    test_sms_service,
)
from university_system.modules.domain.finance.finance_misc.payments import (
    generate_qr_payment_code,
    manual_rate_update,
    process_stripe_payment,
)
from university_system.modules.domain.finance.finance_misc.aid import (
    aid_by_academic_year,
    aid_distribution_summary,
    aid_effectiveness_analysis,
    apply_aid_to_fees,
    approve_reject_aid_application,
    create_aid_type,
    create_payment_arrangement,
    deactivate_aid_type,
    edit_aid_type,
    manage_aid_types,
    process_loan_payment,
    review_pending_aid_applications,
    track_loan_repayments,
    view_aid_application_detail,
    view_aid_types,
)
from university_system.modules.domain.finance.finance_misc.analytics import (
    analyze_fee_structure_impact,
    assign_case_to_agency,
    calculate_growth_rate,
    calculate_seasonal_factors,
    generate_cash_flow_analysis,
    generate_enrollment_projections,
    generate_risk_analysis,
    generate_scenario_planning,
    recovery_rate_analysis,
    start_background_scheduler,
    update_actual_amounts,
    view_overdue_accounts,
)
from university_system.modules.domain.finance.finance_misc.menu import display_enhanced_finance_menu

__all__ = [
    "add_student_credit",
    "aid_by_academic_year",
    "aid_distribution_summary",
    "aid_effectiveness_analysis",
    "analyze_fee_structure_impact",
    "api_get_student_financial_summary",
    "apply_aid_to_fees",
    "apply_credit_to_fees",
    "approve_reject_aid_application",
    "assign_case_to_agency",
    "calculate_growth_rate",
    "calculate_seasonal_factors",
    "check_required_packages",
    "complete_database_fix",
    "create_aid_type",
    "create_payment_arrangement",
    "create_sample_students",
    "deactivate_aid_type",
    "display_enhanced_finance_menu",
    "edit_aid_type",
    "ensure_database_exists",
    "generate_cash_flow_analysis",
    "generate_enrollment_projections",
    "generate_qr_payment_code",
    "generate_risk_analysis",
    "generate_scenario_planning",
    "get_student_email",
    "get_student_name",
    "get_student_phone",
    "init_default_enhanced_data",
    "init_enhanced_finance_db",
    "initialize_finance",
    "manage_aid_types",
    "manual_rate_update",
    "process_loan_payment",
    "process_stripe_payment",
    "quick_fix_database",
    "recovery_rate_analysis",
    "review_pending_aid_applications",
    "send_arrangement_confirmation",
    "send_email_aws_ses",
    "send_email_sendgrid",
    "send_email_smtp",
    "send_sms_aws_sns",
    "send_sms_twilio",
    "set_auth",
    "setup_email_config",
    "setup_sms_config",
    "start_background_scheduler",
    "student_exists",
    "test_email_service",
    "test_sms_service",
    "track_loan_repayments",
    "update_actual_amounts",
    "verify_fix",
    "view_aid_application_detail",
    "view_aid_types",
    "view_credit_history",
    "view_overdue_accounts",
    "view_student_credits",
]
