"""
University System Shared Utilities

This module provides common utilities used across the university system.
"""

from education_system.university_system.modules.shared.utils import state
from education_system.university_system.modules.shared.utils import templates
from education_system.university_system.modules.shared.utils.config import (
    CONFIG_SCHEMA,
    DEFAULT_CONFIG,
    config,
    validate_email_config,
    load_config,
    save_config,
    validate_config,
    configure_email_settings,
    test_email_configuration,
    ensure_email_config_for_database_mode
)
from education_system.university_system.modules.shared.utils.logs import (
    get_log_file,
    configure_logging,
    log_event,
    handle_exception,
    display_communication_logs_menu,
    display_activity_logs,
    export_communication_logs,
    display_communication_analytics_menu,
    logger
)
from education_system.university_system.modules.shared.utils.activity_logger import (
    set_user,
    get_user,
    log_activity,
    log_login,
    log_logout,
    log_create,
    log_read,
    log_update,
    log_delete,
    log_search,
    log_export,
    log_import,
    log_error,
    log_access,
    log_permission_denied,
    logger as activity_logger
)
from education_system.university_system.modules.shared.utils.input_validation import (
    ValidationError,
    validate_required,
    validate_email,
    validate_phone,
    validate_date,
    validate_numeric,
    validate_integer,
    validate_student_id,
    validate_username,
    validate_choice,
    validate_length,
    validate_pattern,
    validate_money,
    validate_percentage,
    get_validated_input,
    InputValidator,
    input_validator,
)
from education_system.university_system.modules.shared.utils.i18n import (
    init_i18n,
    get_text,
    set_language,
    get_current_language,
    get_current_language_name,
    get_available_languages,
    get_available_language_list,
    SUPPORTED_LANGUAGES,
)
from education_system.university_system.modules.shared.utils.language_selector import (
    display_language_selector,
    display_language_menu_option,
    get_startup_language_choice,
)

__all__ = [
    'state',
    'templates',
    'CONFIG_SCHEMA',
    'DEFAULT_CONFIG',
    'config',
    'validate_email_config',
    'load_config',
    'save_config',
    'validate_config',
    'configure_email_settings',
    'test_email_configuration',
    'ensure_email_config_for_database_mode',
    'get_log_file',
    'configure_logging',
    'log_event',
    'handle_exception',
    'display_communication_logs_menu',
    'display_activity_logs',
    'export_communication_logs',
    'display_communication_analytics_menu',
    'logger',
    # Activity logging
    'set_user',
    'get_user',
    'log_activity',
    'log_login',
    'log_logout',
    'log_create',
    'log_read',
    'log_update',
    'log_delete',
    'log_search',
    'log_export',
    'log_import',
    'log_error',
    'log_access',
    'log_permission_denied',
    'activity_logger',
    # Input validation
    'ValidationError',
    'validate_required',
    'validate_email',
    'validate_phone',
    'validate_date',
    'validate_numeric',
    'validate_integer',
    'validate_student_id',
    'validate_username',
    'validate_choice',
    'validate_length',
    'validate_pattern',
    'validate_money',
    'validate_percentage',
    'get_validated_input',
    'InputValidator',
    'input_validator',
    # Internationalization (i18n)
    'init_i18n',
    'get_text',
    'set_language',
    'get_current_language',
    'get_current_language_name',
    'get_available_languages',
    'get_available_language_list',
    'SUPPORTED_LANGUAGES',
    # Language selector
    'display_language_selector',
    'display_language_menu_option',
    'get_startup_language_choice',
]