"""Reports mixin for the Legal Services GUI."""

from education_system.university_system.modules.domain.legal.gui._imports import (
    tk, ttk, messagebox, scrolledtext, filedialog, simpledialog, traceback,
    datetime,
    CaseManager, ConsultationManager, PaymentManager,
    log_activity,
    _t, logger,
    send_email, EMAIL_AVAILABLE,
)


class ReportsMixin:
    """Reports & Analytics tab: generate, email, save reports."""

    def create_reports_tab(self):
        """Create reports and analytics tab"""
        tab = ttk.Frame(self.notebook)
        self.notebook.add(tab, text=_t("legal.tabs.reports", default="Reports & Analytics"))

        # Report options
        options_frame = ttk.LabelFrame(tab, text=_t("legal.reports.title", default="Report Options"), padding="10")
        options_frame.pack(fill=tk.X, padx=10, pady=10)

        # Date range
        ttk.Label(options_frame, text=_t("legal.labels.start_date", default="Start Date") + ":").grid(row=0, column=0, sticky=tk.W, padx=5, pady=5)
        self.report_start = ttk.Entry(options_frame, width=15)
        self.report_start.insert(0, (datetime.now().replace(day=1)).strftime('%Y-%m-%d'))
        self.report_start.grid(row=0, column=1, padx=5, pady=5)

        ttk.Label(options_frame, text=_t("legal.labels.end_date", default="End Date") + ":").grid(row=0, column=2, sticky=tk.W, padx=5, pady=5)
        self.report_end = ttk.Entry(options_frame, width=15)
        self.report_end.insert(0, datetime.now().strftime('%Y-%m-%d'))
        self.report_end.grid(row=0, column=3, padx=5, pady=5)

        # Report type
        ttk.Label(options_frame, text=_t("legal.labels.report_type", default="Report Type") + ":").grid(row=0, column=4, sticky=tk.W, padx=5, pady=5)
        self.report_type = ttk.Combobox(options_frame, values=[
            _t("legal.reports.monthly_summary", default="Monthly Summary"),
            _t("legal.reports.case_statistics", default="Case Statistics"),
            _t("legal.reports.revenue_report", default="Revenue Report"),
            _t("legal.reports.lawyer_performance", default="Lawyer Performance")
        ], state='readonly', width=20)
        self.report_type.set(_t("legal.reports.monthly_summary", default="Monthly Summary"))
        self.report_type.grid(row=0, column=5, padx=5, pady=5)

        ttk.Button(options_frame, text=_t("legal.btn.generate_report", default="Generate Report"), command=self.generate_admin_report).grid(row=0, column=6, padx=10, pady=5)

        # Report display
        report_frame = ttk.LabelFrame(tab, text=_t("legal.report_output", default="Report Output"), padding="10")
        report_frame.pack(fill=tk.BOTH, expand=True, padx=10, pady=5)

        self.report_text = scrolledtext.ScrolledText(report_frame, wrap=tk.WORD, font=('Courier', 10))
        self.report_text.pack(fill=tk.BOTH, expand=True)

        # Action buttons
        btn_frame = ttk.Frame(tab)
        btn_frame.pack(fill=tk.X, padx=10, pady=10)

        ttk.Button(btn_frame, text=_t("legal.btn.email_report", default="Email Report to Admin"), command=self.email_admin_report).pack(side=tk.LEFT, padx=5)
        ttk.Button(btn_frame, text=_t("common.save", default="Save Report"), command=self.save_report).pack(side=tk.LEFT, padx=5)
        ttk.Button(btn_frame, text=_t("common.clear", default="Clear"), command=lambda: self.report_text.delete('1.0', tk.END)).pack(side=tk.RIGHT, padx=5)

    def generate_admin_report(self):
        """Generate comprehensive report for admin"""
        try:
            start_date = self.report_start.get().strip()
            end_date = self.report_end.get().strip()
            report_type = self.report_type.get()

            # Clear previous report
            self.report_text.delete('1.0', tk.END)

            # Get statistics
            case_stats = CaseManager.get_case_statistics()
            revenue_stats = PaymentManager.get_revenue_statistics(start_date, end_date)
            upcoming = ConsultationManager.get_upcoming_consultations(7)

            report = f"""
{'='*70}
            UNIVERSITY LEGAL AID CENTER - {report_type.upper()}
{'='*70}

Report Period: {start_date} to {end_date}
Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
Generated By: {self.current_user.get('username', 'Admin')}

{'='*70}
                        CASE STATISTICS
{'='*70}

Total Cases: {case_stats.get('total_cases', 0)}
Cases This Month: {case_stats.get('cases_this_month', 0)}

By Status:
"""
            for status, count in case_stats.get('by_status', {}).items():
                report += f"  - {status.title()}: {count}\n"

            report += f"""
By Type:
"""
            for case_type, count in case_stats.get('by_type', {}).items():
                report += f"  - {case_type.replace('_', ' ').title()}: {count}\n"

            report += f"""
{'='*70}
                        FINANCIAL SUMMARY
{'='*70}

Total Revenue:        GBP {revenue_stats.get('total_revenue', 0):.2f}
Total Refunds:        GBP {revenue_stats.get('total_refunds', 0):.2f}
Net Revenue:          GBP {revenue_stats.get('net_revenue', 0):.2f}

By Payment Type:
"""
            for ptype, data in revenue_stats.get('by_payment_type', {}).items():
                report += f"  - {ptype.replace('_', ' ').title()}: GBP {data['total']:.2f} ({data['count']} transactions)\n"

            report += f"""
By Payment Method:
"""
            for method, data in revenue_stats.get('by_payment_method', {}).items():
                if method:
                    report += f"  - {method}: GBP {data['total']:.2f} ({data['count']} transactions)\n"

            report += f"""
{'='*70}
                    UPCOMING CONSULTATIONS (Next 7 Days)
{'='*70}

"""
            if upcoming:
                for consult in upcoming[:10]:
                    report += f"  {consult['scheduled_date']} at {consult['scheduled_time']} - {consult['client_name']} ({consult['consultation_type']})\n"
            else:
                report += "  No upcoming consultations scheduled.\n"

            report += f"""
{'='*70}
                              END OF REPORT
{'='*70}
"""

            self.report_text.insert('1.0', report)

            messagebox.showinfo(
                _t("common.success", default="Success"),
                _t("legal.messages.report_generated", default="Report generated successfully")
            )

        except Exception as e:
            messagebox.showerror(_t("common.error", default="Error"), str(e))
            print(f"Error generating report: {traceback.format_exc()}")

    def email_admin_report(self):
        """Email the generated report to admin"""
        report_content = self.report_text.get('1.0', tk.END).strip()

        if not report_content:
            messagebox.showwarning(
                _t("common.warning", default="Warning"),
                _t("legal.warnings.generate_report_first", default="Please generate a report first")
            )
            return

        # Get admin email
        admin_email = simpledialog.askstring(
            _t("legal.btn.email_report", default="Email Report"),
            _t("legal.prompts.admin_email", default="Enter admin email address:"),
            initialvalue=self.admin_email
        )

        if not admin_email:
            return

        if '@' not in admin_email:
            logger.info(f"Report email skipped - invalid email format: {admin_email}")
            messagebox.showwarning(_t("common.warning", default="Warning"), "Invalid email address")
            return

        try:
            report_type = self.report_type.get()
            subject = f"Legal Services Report - {report_type} - {datetime.now().strftime('%Y-%m-%d')}"

            if EMAIL_AVAILABLE:
                result = send_email(
                    recipient_email=admin_email,
                    subject=subject,
                    body=report_content
                )

                if result:
                    messagebox.showinfo(
                        _t("common.success", default="Success"),
                        _t("legal.messages.report_emailed", default="Report sent to admin successfully")
                    )
                    log_activity('email_report', 'legal_services', details={
                        'recipient': admin_email,
                        'report_type': report_type
                    })
                else:
                    messagebox.showerror(
                        _t("common.error", default="Error"),
                        _t("legal.errors.email_failed", default="Failed to send email")
                    )
            else:
                messagebox.showwarning(
                    _t("common.warning", default="Warning"),
                    _t("legal.warnings.email_unavailable", default="Email service not available")
                )

        except Exception as e:
            messagebox.showerror(_t("common.error", default="Error"), str(e))
            print(f"Error emailing report: {traceback.format_exc()}")

    def save_report(self):
        """Save the current report to file"""
        report_content = self.report_text.get('1.0', tk.END).strip()
        if not report_content:
            messagebox.showwarning(_t("common.warning", default="Warning"), "No report to save")
            return

        file_path = filedialog.asksaveasfilename(
            defaultextension=".txt",
            filetypes=[("Text Files", "*.txt"), ("All Files", "*.*")],
            initialfile=f"legal_report_{datetime.now().strftime('%Y%m%d')}.txt"
        )

        if file_path:
            with open(file_path, 'w') as f:
                f.write(report_content)
            messagebox.showinfo(_t("common.success", default="Success"), "Report saved successfully")
