"""Reorganised helpers for academic grading utilities."""

from __future__ import annotations

from university_system.modules.domain.academics.grade_misc.grade_db_init import init_basic_database
from university_system.modules.domain.academics.grade_misc.utils import (
    _get_calculate_course_statistics,
    calculate_trend_slope,
    letter_to_percentage,
    percentage_to_letter,
    select_student,
)
from university_system.modules.domain.academics.grade_misc.reports import (
    generate_all_courses_stats_report,
    generate_all_modules_stats_report,
    generate_comprehensive_stats_report,
    generate_course_stats_report,
    generate_module_stats_report,
    generate_statistical_report,
)
from university_system.modules.domain.academics.grade_misc.competency import manage_competencies, record_student_competencies
from university_system.modules.domain.academics.grade_misc.progress import (
    analyze_student_progress,
    calculate_all_students_success_probability,
    calculate_individual_success_probability,
    calculate_student_success_probability,
    collect_dashboard_data,
    create_progress_visualization,
    save_intervention_recommendations,
    student_progress_tracking,
    success_probability_calculator,
)
from university_system.modules.domain.academics.grade_misc.interventions import (
    display_intervention_recommendations,
    generate_intervention_plan,
    generate_system_recommendations,
    intervention_recommendations,
)
from university_system.modules.domain.academics.grade_misc.comparisons import (
    compare_by_assessment_type,
    compare_by_course,
    compare_by_enrollment_date,
    compare_by_gender,
    compare_by_module_codes,
    compare_by_module_type,
    compare_by_specific_courses,
    compare_by_time_period,
    custom_group_comparison,
    display_course_comparison,
    perform_statistical_test,
)
from university_system.modules.domain.academics.grade_misc.trends import (
    analyze_academic_term_patterns,
    analyze_day_of_week_patterns,
    analyze_individual_student_trends,
    analyze_monthly_patterns,
    analyze_seasonal_trends,
    analyze_single_course_trends,
    create_course_comparison_charts,
    create_individual_trend_visualization,
    create_trend_visualization,
    trend_forecasting,
)
from university_system.modules.domain.academics.grade_misc.forecasting import (
    build_module_success_model,
    create_dashboard_visualizations,
    export_batch_predictions,
    export_comparison_data,
    extract_comprehensive_student_features,
    extract_student_features,
    forecast_course_success_rate,
    forecast_module_difficulty,
    forecast_module_difficulty_single,
    forecast_single_course,
    forecast_success_rates,
    generate_dashboard_alerts,
    generate_dashboard_recommendations,
    generate_dashboard_report,
)

__all__ = [
    "_get_calculate_course_statistics",
    "analyze_academic_term_patterns",
    "analyze_day_of_week_patterns",
    "analyze_individual_student_trends",
    "analyze_monthly_patterns",
    "analyze_seasonal_trends",
    "analyze_single_course_trends",
    "analyze_student_progress",
    "build_module_success_model",
    "calculate_all_students_success_probability",
    "calculate_individual_success_probability",
    "calculate_student_success_probability",
    "calculate_trend_slope",
    "collect_dashboard_data",
    "compare_by_assessment_type",
    "compare_by_course",
    "compare_by_enrollment_date",
    "compare_by_gender",
    "compare_by_module_codes",
    "compare_by_module_type",
    "compare_by_specific_courses",
    "compare_by_time_period",
    "create_course_comparison_charts",
    "create_dashboard_visualizations",
    "create_individual_trend_visualization",
    "create_progress_visualization",
    "create_trend_visualization",
    "custom_group_comparison",
    "display_course_comparison",
    "display_intervention_recommendations",
    "export_batch_predictions",
    "export_comparison_data",
    "extract_comprehensive_student_features",
    "extract_student_features",
    "forecast_course_success_rate",
    "forecast_module_difficulty",
    "forecast_module_difficulty_single",
    "forecast_single_course",
    "forecast_success_rates",
    "generate_all_courses_stats_report",
    "generate_all_modules_stats_report",
    "generate_comprehensive_stats_report",
    "generate_course_stats_report",
    "generate_dashboard_alerts",
    "generate_dashboard_recommendations",
    "generate_dashboard_report",
    "generate_intervention_plan",
    "generate_module_stats_report",
    "generate_statistical_report",
    "generate_system_recommendations",
    "init_basic_database",
    "intervention_recommendations",
    "letter_to_percentage",
    "manage_competencies",
    "percentage_to_letter",
    "perform_statistical_test",
    "record_student_competencies",
    "save_intervention_recommendations",
    "select_student",
    "student_progress_tracking",
    "success_probability_calculator",
    "trend_forecasting",
]
