"""Unit tests for the grades-gated admissions-selection helpers.

Covers UCAS tariff calculation, eligibility gating, and the per-course
18-module (6/year x 3) curriculum generation used by the reworked student
create flow.
"""

import pytest

from education_system.post_18.university_system.modules.domain.academics.services import (
    admissions_selection as A,
)
from education_system.post_18.university_system.modules.domain.academics.services.admissions_selection import (
    curriculum as curr,
)


# --- Tariff -----------------------------------------------------------------

def test_compute_tariff_typical():
    assert A.compute_tariff(["A", "B", "B"]) == 128  # 48 + 40 + 40


def test_compute_tariff_top_and_bottom():
    assert A.compute_tariff(["A*", "A*", "A*"]) == 168
    assert A.compute_tariff(["E", "E", "E"]) == 48


def test_grade_points_and_normalisation():
    assert A.grade_points("a*") == 56
    assert A.grade_points("A") == 48
    assert A.grade_points("nonsense") == 0
    assert A.normalise_grade(" b ") == "B"
    assert A.normalise_grade("Z") == ""


def test_format_qualifications():
    out = A.format_qualifications([("Maths", "A"), ("Physics", "b")])
    assert out == "Maths:A, Physics:B"


# --- Eligibility ------------------------------------------------------------

def test_is_eligible_boundary():
    course = {"code": "CS", "name": "Computer Science", "min_tariff": 112}
    assert A.is_eligible(course, 112) is True   # exactly meets
    assert A.is_eligible(course, 120) is True
    assert A.is_eligible(course, 111) is False


def test_is_eligible_zero_requirement():
    course = {"code": "X", "name": "Open", "min_tariff": 0}
    assert A.is_eligible(course, 0) is True


# --- Curriculum -------------------------------------------------------------

def test_build_entries_structure_seeded():
    entries = curr._build_entries("CS", "Computer Science")
    assert len(entries) == curr.TOTAL_MODULES == 18
    by_year = {}
    for e in entries:
        by_year.setdefault(e["year"], []).append(e)
    assert sorted(by_year) == [1, 2, 3]
    assert all(len(v) == curr.MODULES_PER_YEAR == 6 for v in by_year.values())
    # codes are unique and namespaced to the course
    codes = [e["module_code"] for e in entries]
    assert len(set(codes)) == 18
    assert all(c.startswith("CS-Y") for c in codes)
    # seeded course has real names, not the generic fallback
    assert "Programming Fundamentals" in {e["module_name"] for e in entries}


def test_build_entries_autogenerated_for_unknown_course():
    # Use a course code with no seeded curriculum to exercise the fallback.
    entries = curr._build_entries("ZZZ", "Underwater Basket Weaving")
    assert len(entries) == 18
    names = {e["module_name"] for e in entries}
    assert "Underwater Basket Weaving Year 1 Module 1" in names
    assert all(e["module_code"].startswith("ZZZ-Y") for e in entries)


def test_module_code_format():
    assert curr.module_code("CS", 2, 3) == "CS-Y2-3"
    assert curr.module_code("Data Sci!", 1, 6).startswith("DATASC-Y1-6")
