from education_system.university_system.modules.domain.academics.mitigating_circumstances.cli.mitigating_circumstances_cli import display_mitigating_circumstances_menu

__all__ = ["display_mitigating_circumstances_menu"]
