from education_system.university_system.infrastructure.database.db import sqlite3, get_connection
from datetime import datetime, timedelta
import importlib
from education_system.university_system.modules.domain.health.records.db.audit import log_audit_event
from education_system.university_system.modules.domain.health.records.db.schema import ensure_student_dob_compat


def generate_custom_report(auth):
    """Delegate to health_misc.generate_custom_report with lazy import.
       If the DB is missing expected columns, auto-migrate and retry once.
    """
    import importlib
    try:
        hm = importlib.import_module('src.services.health_misc')
        return hm.generate_custom_report(auth)
    except sqlite3.OperationalError as e:
        msg = str(e)
        if "no such column: date_of_birth" in msg or "no such column: dob" in msg:
            # Heal schema and retry once
            ensure_student_dob_compat()
            try:
                hm = importlib.import_module('src.services.health_misc')
                return hm.generate_custom_report(auth)
            except Exception as e2:
                print(f"Custom report generator unavailable after schema fix: {e2}")
                input("\nPress Enter to return...")
        else:
            print(f"Custom report generator unavailable: {e}")
            input("\nPress Enter to return...")
    except Exception as e:
        print(f"Custom report generator unavailable: {e}")
        input("\nPress Enter to return...")



def generate_public_health_report(auth):
    if not auth.check_permission('issue_health_advisories'):
        print("You don't have permission to generate public health reports.")
        return

    conn = get_connection()
    cursor = conn.cursor()

    print("\n===== Public Health Report Generator =====")

    # Report parameters
    report_types = [
        'Weekly Surveillance Summary',
        'Monthly Disease Report',
        'Outbreak Investigation Report',
        'Vaccination Coverage Report',
        'Custom Analysis Report'
    ]

    print("Report Types:")
    for i, report_type in enumerate(report_types):
        print(f"{i+1}. {report_type}")

    while True:
        choice = input("\nSelect report type (1-5): ")
        if choice.isdigit() and 1 <= int(choice) <= len(report_types):
            selected_report = report_types[int(choice) - 1]
            break
        print("Invalid choice. Please try again.")

    # Date range
    if selected_report == 'Weekly Surveillance Summary':
        end_date = datetime.now()
        start_date = end_date - timedelta(days=7)
    elif selected_report == 'Monthly Disease Report':
        end_date = datetime.now()
        start_date = end_date - timedelta(days=30)
    else:
        while True:
            start_date_str = input("Start date (YYYY-MM-DD): ")
            end_date_str = input("End date (YYYY-MM-DD): ")
            try:
                start_date = datetime.strptime(start_date_str, '%Y-%m-%d')
                end_date = datetime.strptime(end_date_str, '%Y-%m-%d')
                break
            except ValueError:
                print("Invalid date format. Please use YYYY-MM-DD.")

    start_date_str = start_date.strftime('%Y-%m-%d')
    end_date_str = end_date.strftime('%Y-%m-%d')

    print(f"\nGenerating {selected_report}")
    print(f"Period: {start_date_str} to {end_date_str}")

    # Generate report content
    report_content = []
    report_content.append(f"=== {selected_report} ===")
    report_content.append(f"Report Period: {start_date_str} to {end_date_str}")
    report_content.append(f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    report_content.append(f"Generated by: {auth.current_user['username']}")
    report_content.append("")

    # Disease surveillance data
    cursor.execute('''
    SELECT disease_name, COUNT(*) as case_count,
           SUM(CASE WHEN severity IN ('Severe', 'Critical') THEN 1 ELSE 0 END) as severe_cases
    FROM disease_surveillance
    WHERE case_date BETWEEN ? AND ?
    GROUP BY disease_name
    ORDER BY case_count DESC
    ''', (start_date_str, end_date_str))

    disease_data = cursor.fetchall()

    if disease_data:
        report_content.append("DISEASE SURVEILLANCE SUMMARY")
        report_content.append("-" * 30)
        total_cases = sum(count for _, count, _ in disease_data)
        report_content.append(f"Total Cases: {total_cases}")
        report_content.append("")

        for disease, count, severe in disease_data:
            report_content.append(f"{disease}: {count} cases ({severe} severe)")

    # Vaccination data
    cursor.execute('''
    SELECT vaccine_name, COUNT(*) as doses_administered
    FROM vaccination_records
    WHERE administered_date BETWEEN ? AND ?
    GROUP BY vaccine_name
    ORDER BY doses_administered DESC
    ''', (start_date_str, end_date_str))

    vaccination_data = cursor.fetchall()

    if vaccination_data:
        report_content.append("")
        report_content.append("VACCINATION SUMMARY")
        report_content.append("-" * 20)
        total_doses = sum(count for _, count in vaccination_data)
        report_content.append(f"Total Doses: {total_doses}")
        report_content.append("")

        for vaccine, count in vaccination_data:
            report_content.append(f"{vaccine}: {count} doses")

    # Health advisories
    cursor.execute('''
    SELECT title, priority, effective_date
    FROM health_advisories
    WHERE effective_date BETWEEN ? AND ?
    ORDER BY priority DESC, effective_date DESC
    ''', (start_date_str, end_date_str))

    advisory_data = cursor.fetchall()

    if advisory_data:
        report_content.append("")
        report_content.append("HEALTH ADVISORIES ISSUED")
        report_content.append("-" * 25)

        for title, priority, date in advisory_data:
            report_content.append(f"{date} - {title} ({priority} priority)")

    # Key recommendations
    report_content.append("")
    report_content.append("KEY RECOMMENDATIONS")
    report_content.append("-" * 20)

    # Generate recommendations based on data
    recommendations = []

    if disease_data:
        high_count_diseases = [disease for disease, count, _ in disease_data if count >= 5]
        if high_count_diseases:
            recommendations.append(f"Enhanced surveillance recommended for: {', '.join(high_count_diseases)}")

    if vaccination_data:
        if total_doses < 50:  # Arbitrary threshold
            recommendations.append("Consider vaccination outreach campaigns")

    recommendations.append("Continue routine surveillance activities")
    recommendations.append("Monitor for seasonal disease patterns")

    for rec in recommendations:
        report_content.append(f"• {rec}")

    # Display report
    print("\n" + "="*60)
    for line in report_content:
        print(line)
    print("="*60)

    # Save report option
    save_report = input("\nSave report to file? (y/n): ").lower()
    if save_report == 'y':
        timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
        filename = f"public_health_report_{timestamp}.txt"

        try:
            with open(filename, 'w', encoding='utf-8') as f:
                for line in report_content:
                    f.write(line + '\n')

            log_audit_event(auth.current_user['id'], 'generate_public_health_report', 'report', filename)
            print(f"Report saved to: {filename}")
        except Exception as e:
            print(f"Error saving report: {e}")

    conn.close()



